import type { ProjectService } from '../projects.ts';
import type { ProjectSnapshot,FileChange } from '../../shared/model.ts';
import { asString,asStrings,asRows,asNumber,asData,type CreativeObject,type Data } from '../../shared/creative/model.ts';
import { buildCreativeIndex,objectBlock,replaceObject,objectContext } from '../../shared/creative/content.ts';
import { prepareJobs,productionJobs,jobStale,type ProductionBundle,type ProductionOptions } from '../../shared/creative/production.ts';
import { compileSequence } from '../../shared/creative/sequence.ts';
import { ProjectError } from '../files.ts';
import { Buffer } from '../platform.ts';
const safe=(value:unknown)=>{const id=asString(value);if(!/^[A-Za-z0-9_-]{1,120}$/.test(id))throw new ProjectError('INVALID_ID','身份无效');return id;};
function locate(snapshot:ProjectSnapshot,id:string){const value=buildCreativeIndex(snapshot).objects.find(x=>x.object.id===id);if(!value)throw new ProjectError('MISSING_OBJECT',`未找到对象 ${id}`);return value;}
function options(input:Record<string,unknown>):ProductionOptions {if(input.scope!==undefined&&!['all','missing','changed'].includes(asString(input.scope)))throw new ProjectError('INVALID_SCOPE','任务范围无效');return {scope:asString(input.scope,'all') as ProductionOptions['scope'],...(input.selectedJobIds!==undefined?{selectedJobIds:asStrings(input.selectedJobIds)}:{}),overrides:asData(input.overrides) as ProductionOptions['overrides']};}
function ensure(snapshot:ProjectSnapshot){if(snapshot.project.format!==2)throw new ProjectError('FORMAT_UPGRADE_REQUIRED','生产需要格式 2 项目');}
/** 产线只产生候选。回导与采用独立，正式采用仍有完整基准与事务日志。 */
export class ProductionService {
 constructor(private projects:ProjectService){}
 async preview(id:string,input:Record<string,unknown>){const snapshot=await this.projects.read(id);ensure(snapshot);const batchId=safe(input.batchId),targetIds=asStrings(input.targetIds);if(!targetIds.length||targetIds.length>100)throw new ProjectError('INVALID_SCOPE','选择 1～100 个对象');return {format:'cewen-production-1',projectId:id,batchId,sourceRevision:snapshot.revision,jobs:prepareJobs(buildCreativeIndex(snapshot),targetIds,batchId,snapshot.revision,options(input)),instructions:'按任务 ID 返回文件与 cewen-results-1 清单；回导不表示采用。'} satisfies ProductionBundle;}
 async prepare(id:string,input:Record<string,unknown>){const snapshot=await this.projects.read(id);ensure(snapshot);return this.projects.runOperation(id,{...input,requestId:safe(input.requestId)},()=>{if(input.baseRevision!==undefined&&input.baseRevision!==snapshot.revision)throw new ProjectError('PREVIEW_STALE','项目在预览后已经变化，请重新预览再确认');const batchId=safe(input.batchId),jobs=prepareJobs(buildCreativeIndex(snapshot),asStrings(input.targetIds),batchId,snapshot.revision,options(input));if(jobs.length>500||!jobs.length)throw new ProjectError('JOB_LIMIT','每批 1～500 个任务');
  const o:CreativeObject={id:batchId,schema:1,type:'production',title:asString(input.title,'素材生产批次').slice(0,200),status:'draft',data:{purpose:asString(input.purpose),provider:asString(input.provider,'通用文件包'),sourceRevision:snapshot.revision,jobs:JSON.parse(JSON.stringify(jobs))}};
  return {projectId:id,requestId:asString(input.requestId),baseRevision:snapshot.revision,actor:'user',reason:`准备生产任务：${o.title}`,changes:[{path:`docs/production/${batchId}.md`,baseHash:null,text:`---\nid: doc-${batchId}\ntype: guide\nstatus: draft\n---\n\n# ${o.title.replace(/[\r\n]/g,' ')}\n\n生成任务是候选任务，不表示已提交外部服务。\n\n${objectBlock(o)}\n`}]};});}
 async read(id:string,batchId:string){const snapshot=await this.projects.read(id),index=buildCreativeIndex(snapshot),located=locate(snapshot,batchId);if(located.object.type!=='production')throw new ProjectError('INVALID_BATCH','不是生产批次');return {revision:snapshot.revision,batch:located.object,hash:located.hash,jobs:productionJobs(located.object.data).map(j=>({...j,stale:jobStale(index,j)}))};}
 async recordResult(id:string,input:Record<string,unknown>){const snapshot=await this.projects.read(id);ensure(snapshot);return this.projects.runOperation(id,{...input,requestId:safe(input.requestId)},()=>{
  const located=locate(snapshot,safe(input.batchId)),batch=structuredClone(located.object);if(batch.type!=='production')throw new ProjectError('INVALID_BATCH','不是生产批次');const jobs=productionJobs(batch.data),job=jobs.find(j=>j.id===input.jobId);if(!job)throw new ProjectError('WRONG_JOB','结果任务不属于本批次');
  const candidateId=safe(input.candidateId),media=locate(snapshot,safe(input.mediaId)).object;if(media.type!=='media'||!asString(media.data.mime).startsWith(job.kind==='voice'?'audio/':'image/'))throw new ProjectError('WRONG_MEDIA_TYPE','结果媒体类型与任务不匹配');
  const old=job.candidates.find(c=>c.id===candidateId);if(old&&old.mediaId!==media.id)throw new ProjectError('CANDIDATE_CONFLICT','同候选身份不能换成另一文件');if(!old)job.candidates.push({id:candidateId,mediaId:media.id,createdAt:new Date().toISOString(),stale:jobStale(buildCreativeIndex(snapshot),job)});job.state=job.adoptedMediaId?'adopted':'returned';batch.data.jobs=JSON.parse(JSON.stringify(jobs));
  const doc=snapshot.documents.find(d=>d.id===located.documentId)!;return {projectId:id,requestId:asString(input.requestId),baseRevision:snapshot.revision,actor:'user',reason:`登记候选：${job.title}`,changes:[{path:doc.path,baseHash:doc.hash,text:replaceObject(doc.text,located,batch)}]};});}
 async adopt(id:string,input:Record<string,unknown>){const snapshot=await this.projects.read(id);ensure(snapshot);return this.projects.runOperation(id,{...input,requestId:safe(input.requestId)},()=>{
  const located=locate(snapshot,safe(input.batchId)),batch=structuredClone(located.object),jobs=productionJobs(batch.data),job=jobs.find(j=>j.id===input.jobId),candidate=job?.candidates.find(c=>c.id===input.candidateId);if(!job||!candidate)throw new ProjectError('MISSING_CANDIDATE','没有这个候选');
  if(jobStale(buildCreativeIndex(snapshot),job))throw new ProjectError('STALE_RESULT','生成依据已经变化，请重新准备任务；旧候选保留，不自动采用');
  const target=locate(snapshot,job.targetId),object=structuredClone(target.object);if(input.baseHash!==target.hash)throw new ProjectError('OBJECT_CONFLICT','目标已变化，请重新核对');
  if(job.panelId){const panel=asRows(object.data.panels).find(p=>p.id===job.panelId);if(!panel)throw new ProjectError('MISSING_PANEL','目标画面已移除');panel.mediaId=candidate.mediaId;}else object.data.mediaId=candidate.mediaId;
  const changes=new Map<string,FileChange>(),targetDoc=snapshot.documents.find(d=>d.id===target.documentId)!;changes.set(targetDoc.path,{path:targetDoc.path,baseHash:targetDoc.hash,text:replaceObject(targetDoc.text,target,object)});
  job.state='adopted';job.adoptedMediaId=candidate.mediaId;batch.data.jobs=JSON.parse(JSON.stringify(jobs));const doc=snapshot.documents.find(d=>d.id===located.documentId)!;
  if(changes.has(doc.path))throw new ProjectError('INVALID_BATCH_LOCATION','生产清单必须保存在独立管理文档');changes.set(doc.path,{path:doc.path,baseHash:doc.hash,text:replaceObject(doc.text,located,batch)});
  return {projectId:id,requestId:asString(input.requestId),baseRevision:snapshot.revision,actor:'user',reason:`采用素材：${job.title}`,changes:[...changes.values()]};});}
 /** 文件包可独立交接；只嵌入明确依赖的参考媒体，不含私人工作区。 */
 async bundle(id:string,batchId:string){const snapshot=await this.projects.read(id),located=locate(snapshot,batchId);if(located.object.type!=='production')throw new ProjectError('INVALID_BATCH','不是生产批次');const jobs=productionJobs(located.object.data),mediaIds=[...new Set(jobs.flatMap(j=>j.referenceMediaIds))],assets:{id:string;path:string;mime:string;sha256:string;data:string}[]=[];let bytes=0;
  for(const mediaId of mediaIds){const o=locate(snapshot,mediaId).object,blob=await this.projects.asset(id,asString(o.data.path));bytes+=blob.length;if(bytes>32*1024*1024)throw new ProjectError('BUNDLE_TOO_LARGE','参考媒体超过 32 MiB，请拆分批次');assets.push({id:mediaId,path:asString(o.data.path),mime:asString(o.data.mime),sha256:asString(o.data.sha256),data:blob.toString('base64')});}
  return {format:'cewen-production-1',projectId:id,batchId,sourceRevision:located.object.data.sourceRevision,jobs,assets,instructions:'每个候选返回稳定 candidateId，使用 cewen-results-1 清单指定 batchId、jobId、filename、candidateId；不得依据文件排序猜对应关系。',receiptTemplate:{format:'cewen-results-1',batchId,results:jobs.map(j=>({jobId:j.id,filename:`${j.id}.${j.kind==='voice'?'wav':'png'}`,candidateId:`candidate-${j.id}-1`}))}};}
 async playbackBundle(id:string,sequenceId:string,revision?:string){const snapshot=revision?await this.projects.revision(id,revision):await this.projects.read(id),index=buildCreativeIndex(snapshot),plan=compileSequence(index,sequenceId),ids=[...new Set([...plan.frames.map(f=>f.mediaId),...plan.audio.map(a=>a.mediaId)].filter(Boolean))],assets:Record<string,{mime:string;data:string}>={};let size=0;
  for(const mediaId of ids){const o=locate(snapshot,mediaId).object,bytes=await this.projects.asset(id,asString(o.data.path));size+=bytes.length;if(size>48*1024*1024)throw new ProjectError('BUNDLE_TOO_LARGE','排演包媒体超过 48 MiB，请按段导出');assets[mediaId]={mime:asString(o.data.mime),data:bytes.toString('base64')};}
  return {format:'cewen-playback-1',projectId:id,revision:snapshot.revision,plan,assets};}
}
