import type { DocumentPreset } from '../shared/document-presets';
import { h } from './creative/render';
import { buildCreativeIndex } from '../shared/creative/content';
import { moduleRegistry } from '../shared/creative/registry';

/** 预设通过来源、用途和名称检索；没有用户选择时只允许明确的空白创建。 */
export function pickDocumentPreset(presets:DocumentPreset[],manage=false):Promise<{id:string;action:string;name:string}|undefined>{
  return new Promise(resolve=>{
    const dialog=document.createElement('dialog');dialog.className='project-dialog desktop-task-dialog preset-library-dialog';let selected='',query='',source='all';
    dialog.innerHTML=`<form><header><h2>${manage?'文档预设库':'新建基础文档'}</h2><button type="button" data-close aria-label="关闭">×</button></header><div class="preset-picker-filter"><input type="search" placeholder="搜索名称、用途或标签" aria-label="搜索文档预设"/><select aria-label="预设来源"><option value="all">全部来源</option><option value="builtin">官方预设</option><option value="user">我的预设</option></select></div><div class="preset-picker-list" role="listbox" aria-label="文档预设"></div>${manage?'':`<label>文档名称<input name="name" value="新文档" required maxlength="100"/></label>`}<p data-description>${manage?'选中预设后可编辑、复制、置顶或删除。':'尚未选择预设，将创建空白自由画布。'}</p><footer>${manage?'<button type="button" data-action="blank">新建预设</button><button type="button" data-action="copy">复制</button><button type="button" data-action="pin">置顶</button><button type="button" data-action="delete">删除</button><button type="submit" class="primary-button">编辑预设</button>':'<button type="button" data-empty>使用空白文档</button><button type="submit" class="primary-button">创建文档</button>'}</footer></form>`;
    const finish=(action:string)=>{if(manage&&!selected&&action!=='blank')return;const name=String(new FormData(dialog.querySelector('form')!).get('name')??'');dialog.close();dialog.remove();resolve({id:selected,action,name});};
    const render=()=>{dialog.querySelector('.preset-picker-list')!.innerHTML=presets.filter(p=>(source==='all'||p.source===source)&&`${p.name} ${p.purpose} ${p.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())).map(p=>{const count=buildCreativeIndex({documents:[{id:p.id,path:'docs/preset.md',text:p.markdown,title:p.name,hash:'',system:'',type:'dd',status:'draft'}]}).objects;return `<button type="button" role="option" aria-selected="${selected===p.id}" data-preset="${h(p.id)}"><strong>${p.pinned?'★ ':''}${h(p.name)}</strong><small>${p.source==='builtin'?'官方':'我的'} · ${h(p.purpose||'通用')}</small><span>${h(count.map(o=>moduleRegistry.get(o.object.type)?.title??o.object.type).join('、')||'文字与章节')} · 自由画布</span></button>`;}).join('')||'<p>没有匹配的预设。可以从空白创建自己的预设。</p>';};
    dialog.querySelector<HTMLInputElement>('[type=search]')!.oninput=e=>{query=(e.target as HTMLInputElement).value;render();};dialog.querySelector('select')!.onchange=e=>{source=(e.target as HTMLSelectElement).value;render();};
    const close=()=>{dialog.close();dialog.remove();resolve(undefined);};dialog.oncancel=e=>{e.preventDefault();close();};
    dialog.onclick=e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!b)return;if(b.hasAttribute('data-close'))close();if(b.hasAttribute('data-empty')){selected='';render();dialog.querySelector('[data-description]')!.textContent='空白文档，进入后自由插入内容。';}if(b.dataset.preset){selected=b.dataset.preset;render();const preset=presets.find(p=>p.id===selected)!;dialog.querySelector('[data-description]')!.textContent=preset.description;const input=dialog.querySelector<HTMLInputElement>('[name=name]');if(input&&(input.value==='新文档'||presets.some(p=>p.name===input.value)))input.value=preset.name;}if(b.dataset.action)finish(b.dataset.action);};
    dialog.onsubmit=e=>{e.preventDefault();finish(manage?'edit':'create');};render();document.body.append(dialog);dialog.showModal();
  });
}
