import { pickDocumentPreset } from './document-preset-picker';
import type { ProjectSnapshot,ProjectDocument,FileChange,KnowledgeGroup } from '../shared/model';
import { readHeader,parseKnowledge } from '../shared/markdown';
import { setMetadata,setTitle } from '../shared/editing';
import { layoutCompanionPath,type LayoutCompanion } from '../shared/document-companion';
import { builtinDocumentPresets,instantiateDocumentPreset,captureDocumentPreset,type DocumentPreset } from '../shared/document-presets';
import { buildCreativeIndex,objectBlock } from '../shared/creative/content';
import { moduleRegistry } from '../shared/creative/registry';
import { isTransientProject,transientProjects,draftMediaUrls } from '../shared/transient';
import { APP_VERSION } from '../shared/version';
import { DocumentCanvas } from './document-canvas';
import { RichWriting } from './rich-writing';
import { projectMarkdown } from './document-reading';
import { mountCreativeBlocks } from './creative/inline';
import { openObjectEditor } from './creative/editor';
import { detectMedia } from '../shared/creative/media';
import { mediaInput } from './creative/production-panel';
import { CreativeWorkspace } from './creative/workspace';
import { cloneCreativeObject } from '../shared/creative/clone';
import { AnimaticPlayer } from './creative/player';
import { h } from './creative/render';
import { request,listProjects,cacheDraft,deleteDraft,projectDrafts,projectAction,uploadProjectMedia,projectAssetUrl } from './project-client';
import { ProjectLibraryView } from './project-library';
import { projectWizard } from './project-wizard';
import { appForm,appChoice } from './app-dialog';
import { showAppMenu,type AppCommand } from './app-menu';
import { openCollaboration } from './prompt-panel';
import { DOCUMENT_DRAG_TYPE } from './document-drag';
import { resolveDocumentLink } from './markdown-view';
import './document-desktop.css';
import { categoryColor } from './category-color';
import { desktopCommand,applyTheme,currentTheme } from './theme';

/** 每份文档的编辑实例、撤销链和保存基准相互独立；切换标签不会卸载编辑器。 */
interface DocumentTab {
  doc:ProjectDocument; baseText:string|null; baseHash:string|null; layout:LayoutCompanion; baseLayoutHash:string|null;
  dirty:boolean;pinned:boolean;host:HTMLElement;canvas:DocumentCanvas;disposeMedia?:()=>void;assets:FileChange[];preset?:DocumentPreset;
}
export interface DesktopOptions {apply(snapshot:ProjectSnapshot):void;document():void;graph(mode?:'galaxy'|'layers'|'mindmap',documentId?:string):void;history():void;connections():void;proposals():void;legacyAction(detail:{action:string;objectId?:string}):void}

/** 桌面主工作区：项目库 → 项目文档树 → 标签页中的自由画布。 */
export class DocumentDesktop {
  readonly root=document.createElement('section');
  private libraryHost=document.createElement('section');private work=document.createElement('section');private library:ProjectLibraryView;
  private snapshot?:ProjectSnapshot;private tabs=new Map<string,DocumentTab>();private active='';private selected=new Set<string>();private lastSelected='';
  private menu!:HTMLElement;private tree!:HTMLElement;private tabbar!:HTMLElement;private canvases!:HTMLElement;private inspector!:HTMLElement;private footer!:HTMLElement;
  private filter='';private collapsed=new Set<string>();private structure?:{text:string;baseHash:string};private busy=false;private home=true;
  private contextDispose?:()=>void;private sessionChanged=false;
  private inlineDispose?:()=>void;private users:DocumentPreset[]=[];
  /** 移动归属属于项目结构草稿，放弃某页正文不会撤销它。 */
  private removed=new Map<string,ProjectDocument>();
  private moves=new Map<string,{system:string;parent?:string}>();
  private favorites=new Set<string>();private recent:string[]=[];private navFilter='all';
  constructor(private options:DesktopOptions){
    this.root.className='document-desktop';this.libraryHost.className='desktop-library';this.work.className='desktop-work';this.work.hidden=true;
    this.root.append(this.libraryHost,this.work);document.body.append(this.root);
    this.library=new ProjectLibraryView(this.libraryHost,s=>this.open(s),()=>void this.newProject(),()=>void this.examples());
    this.buildShell();
    window.addEventListener('cewen-theme-change',()=>{if(this.snapshot)this.renderTree();});
    window.addEventListener('keydown',e=>{if(this.visible&&!e.defaultPrevented&&!((e.target as HTMLElement).closest('.app-command-menu')))this.key(e);});
    window.addEventListener('cewen:operation-error',e=>this.report((e as CustomEvent).detail));
    window.addEventListener('cewen:editing-command',e=>{if(this.root.hidden||this.home)return;const cmd=(e as CustomEvent<string>).detail;if(!['save','undo','redo'].includes(cmd))return;if(cmd!=='save'&&(document.activeElement as HTMLElement)?.closest('input,textarea,[contenteditable=true]'))return;e.preventDefault();if(cmd==='save')void this.save().catch(err=>this.report(err));if(cmd==='undo')this.current()?.canvas.undo();if(cmd==='redo')this.current()?.canvas.redo();},{capture:true});
    window.addEventListener('beforeunload',e=>{if(this.hasChanges()){e.preventDefault();e.returnValue='';}});
    void this.library.refresh().catch(e=>this.report(e));
  }
  get isHome(){return this.home;}
  get visible(){return !this.root.hidden;}
  private current(){return this.tabs.get(this.active);}
  private hasChanges(){return this.sessionChanged||!!this.removed.size||!!this.structure||!!this.moves.size||[...this.tabs.values()].some(t=>t.dirty);}
  private report(error:unknown){const message=error instanceof Error?error.message:String(error);this.footer.textContent=message;this.footer.setAttribute('data-error','');if(this.home){let box=this.libraryHost.querySelector<HTMLElement>('[role=status]');if(!box){box=document.createElement('p');box.setAttribute('role','status');this.libraryHost.append(box);}box.textContent=message;}}
  private notice(text:string){this.footer.textContent=text;this.footer.removeAttribute('data-error');}
  private buildShell(){
    this.work.innerHTML=`<header class="document-menu"><button data-home>项目库</button><button data-file>文件</button><button data-edit>编辑</button><button data-view>视图</button><button data-presets>文档预设</button><button data-help>帮助</button><strong data-project-title></strong><span data-session-kind></span></header><div class="document-work-grid"><aside class="document-tree-panel"><header><strong>项目文档</strong><button data-new title="新建文档">＋</button><button data-tree-menu aria-label="文档树选项">⋯</button></header><input type="search" placeholder="搜索标题、用途、标签" aria-label="搜索项目文档"/><div class="document-tree" role="tree" aria-label="项目文档树"></div></aside><main class="document-center"><div class="document-tabs" role="tablist"></div><div class="document-canvases"></div></main><aside class="document-properties" aria-label="文档属性"></aside></div><footer class="document-status" role="status" aria-live="polite"></footer>`;
    this.menu=this.work.querySelector('.document-menu')!;
    this.tree=this.work.querySelector('.document-tree')!;this.tabbar=this.work.querySelector('.document-tabs')!;this.canvases=this.work.querySelector('.document-canvases')!;this.inspector=this.work.querySelector('.document-properties')!;this.footer=this.work.querySelector('.document-status')!;
    this.tree.parentElement!.querySelector<HTMLInputElement>('[type=search]')!.oninput=e=>{this.filter=(e.target as HTMLInputElement).value;this.renderTree();};
    const splitter=document.createElement('div');splitter.className='document-sidebar-splitter';splitter.tabIndex=0;splitter.setAttribute('role','separator');splitter.setAttribute('aria-label','调整文档侧栏宽度');splitter.setAttribute('aria-orientation','vertical');this.work.querySelector('.document-tree-panel')!.append(splitter);
    splitter.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();const start=e.clientX,width=this.tree.parentElement!.getBoundingClientRect().width;splitter.setPointerCapture(e.pointerId);const move=(next:PointerEvent)=>this.work.style.setProperty('--tree-width',Math.min(440,Math.max(190,width+next.clientX-start))+'px');const end=()=>{splitter.removeEventListener('pointermove',move);splitter.removeEventListener('pointerup',end);splitter.removeEventListener('pointercancel',end);};splitter.addEventListener('pointermove',move);splitter.addEventListener('pointerup',end);splitter.addEventListener('pointercancel',end);};
    splitter.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();this.work.style.setProperty('--tree-width',Math.min(440,Math.max(190,this.tree.parentElement!.clientWidth+(e.key==='ArrowLeft'?-16:16)))+'px');}};
    const commandClick=(e:MouseEvent)=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!b)return;const run=(p:Promise<unknown>)=>void p.catch(err=>this.report(err));
      if(b.hasAttribute('data-home'))run(this.showLibrary());if(b.hasAttribute('data-new'))run(this.newDocument());if(b.hasAttribute('data-presets'))run(this.presetLibrary());
      if(b.hasAttribute('data-file'))showAppMenu(this.fileCommands(),b);if(b.hasAttribute('data-edit'))showAppMenu([{label:'撤销',shortcut:'Ctrl+Z',run:()=>desktopCommand('undo')},{label:'重做',shortcut:'Ctrl+Y',run:()=>desktopCommand('redo')},...(window.cewenDesktop?[{label:'剪切',run:()=>desktopCommand('cut')},{label:'复制',run:()=>desktopCommand('copy')},{label:'粘贴',run:()=>desktopCommand('paste')},{label:'全选',run:()=>desktopCommand('selectAll')}]:[]),{label:'插入模块…',disabled:this.home,run:()=>this.insert()},{label:'重命名文档…',shortcut:'F2',disabled:this.home,run:()=>this.rename()}],b);
      if(b.hasAttribute('data-view'))showAppMenu([
        {label:'文档画布',disabled:!this.snapshot,run:()=>this.show()},
        {label:'星空视图',disabled:!this.snapshot,run:()=>this.graphView('galaxy')},
        {label:'分类分层视图',disabled:!this.snapshot,run:()=>this.graphView('layers')},
        {label:'思维导图视图',disabled:!this.snapshot,run:()=>this.graphView('mindmap')},
        {label:'当前文档的卡片关系预览',disabled:!this.current()||!!this.current()?.preset,run:()=>this.graphView(undefined,this.active)},
        {label:'文档卡片视图',disabled:!this.snapshot,run:()=>{this.show();this.cards();}},
        {label:'属性侧栏',disabled:this.home,run:()=>{if(innerWidth<1000)this.work.classList.toggle('show-properties');else this.work.classList.toggle('hide-properties');}},
        {label:'文档大纲',disabled:this.home,run:()=>this.outline()},{label:'适应画布',disabled:this.home,run:()=>this.current()?.canvas.fit()},
        {label:'版本历史',disabled:!this.snapshot,run:()=>this.options.history()},{label:'连接与集成',run:()=>this.options.connections()},
        {label:currentTheme()==='dark'?'切换浅色主题':'切换深色主题',separator:true,run:()=>applyTheme(currentTheme()==='dark'?'light':'dark')},
        ...(window.cewenDesktop?[{label:'放大界面',run:()=>desktopCommand('zoomIn')},{label:'缩小界面',run:()=>desktopCommand('zoomOut')},{label:'恢复界面比例',run:()=>desktopCommand('resetZoom')}]:[])
      ],b);
      if(b.hasAttribute('data-help'))showAppMenu([{label:'示例与新手教程',run:()=>this.examples()},{label:'关于策问',run:()=>this.about()}],b);
      if(b.hasAttribute('data-tree-menu'))showAppMenu([{label:'新建基础文档',run:()=>this.newDocument()},{label:'新建分类…',run:()=>this.newCategory()},{label:'新建集合…',run:()=>this.createCollection()},{label:'全部展开',run:()=>{this.collapsed.clear();this.renderTree();}}],b);
    };
    this.work.addEventListener('click',commandClick);
    // 菜单合并到壳栏，浏览器版放入原应用栏；整个软件保留原主面板骨架。
    const chrome=document.querySelector('.desktop-titlebar-content')??document.querySelector('.application-bar');
    if(chrome){chrome.prepend(this.menu);this.menu.addEventListener('click',commandClick);}
    const treePanel=this.tree.parentElement!;document.querySelector('#project-sidebar')!.append(treePanel);treePanel.addEventListener('click',commandClick);
  }
  /** 图谱使用原场景、镜头过渡与关系卡片，保存前不会把新文档伪装成正式关系。 */
  private graphView(mode?:'galaxy'|'layers'|'mindmap',documentId?:string){
    if(!this.snapshot)return;if(documentId&&!this.snapshot.documents.some(d=>d.id===documentId)){this.notice('请先保存新文档，再查看关系。');return;}
    this.root.hidden=true;this.options.graph(mode,documentId);
  }
  private fileCommands():AppCommand[]{return [
    {label:'新建项目…',shortcut:'Ctrl+Shift+N',run:()=>this.newProject()},
    {label:'新建基础文档…',shortcut:'Ctrl+N',disabled:!this.snapshot,run:()=>this.newDocument()},
    {label:'保存当前文档',shortcut:'Ctrl+S',disabled:!this.current(),run:()=>this.save()},
    {label:'保存全部文档与结构',shortcut:'Ctrl+Alt+S',run:()=>this.save(true)},
    {label:'项目另存为…',shortcut:'Ctrl+Shift+S',run:()=>this.saveAs()},
    {label:'保存当前文档为预设…',run:()=>this.capturePreset()},
    {label:'关闭当前标签',shortcut:'Ctrl+W',run:()=>this.closeTab(this.active)},
    {label:'返回项目库',separator:true,run:()=>this.showLibrary()},
    ...(window.cewenDesktop?[{label:'在浏览器打开',run:()=>desktopCommand('browser')},{label:'收起到系统托盘',run:()=>desktopCommand('hide')},{label:'退出策问',run:()=>desktopCommand('quit')}]:[]),
  ];}
  show(){
    this.root.hidden=false;const app=document.getElementById('app')!;
    if(this.home){document.body.append(this.root);this.root.classList.remove('embedded-document-desktop');app.classList.remove('document-canvas-open');app.hidden=true;}
    else{app.hidden=false;document.querySelector('.work-area')!.append(this.root);this.root.classList.add('embedded-document-desktop');this.options.document();}
  }
  private saveNavigation(){if(!this.snapshot||isTransientProject(this.snapshot.project.id))return;try{localStorage.setItem('cewen-desktop-nav:'+this.snapshot.project.id,JSON.stringify({favorites:[...this.favorites],recent:this.recent,collapsed:[...this.collapsed]}));}catch{/* 偏好失效不影响公开文档。 */}}
  private loadNavigation(){this.favorites.clear();this.recent=[];this.collapsed.clear();this.navFilter='all';if(!this.snapshot||isTransientProject(this.snapshot.project.id))return;try{const state=JSON.parse(localStorage.getItem('cewen-desktop-nav:'+this.snapshot.project.id)??'{}');this.favorites=new Set(state.favorites??[]);this.recent=state.recent??[];this.collapsed=new Set(state.collapsed??[]);}catch{/* 使用当前会话的默认导航。 */}}
  async open(snapshot:ProjectSnapshot,admitted=false){if(!admitted&&this.snapshot?.project.id!==snapshot.project.id&&!await this.leave())return;const previous=this.snapshot?.project.id;this.clear();if(previous&&previous!==snapshot.project.id&&isTransientProject(previous))(await import('../browser/transient-projects')).disposeTransient(previous);this.snapshot=snapshot;this.loadNavigation();this.home=false;this.libraryHost.hidden=true;this.work.hidden=false;this.show();this.options.apply(snapshot);this.renderTree();this.updateTitle();const first=this.documents().find(d=>d.path.endsWith('/start.md'))??this.documents()[0];if(first)this.openDocument(first.id);else this.renderTabs();this.notice(isTransientProject(snapshot.project.id)?'临时示例 · 所有编辑仅存于本次会话；保存将另存为新项目。':'单击打开，双击固定标签；空白左键拖动画布，右键拖动框选。');await this.recoverDrafts();}
  /** 外部刷新只更新干净标签；有草稿的标签保留旧哈希供正式保存时判断冲突。 */
  receive(snapshot:ProjectSnapshot){if(this.snapshot?.project.id!==snapshot.project.id||this.home||snapshot.historical)return;if(isTransientProject(snapshot.project.id)&&snapshot.revision!==this.snapshot.revision)this.sessionChanged=true;this.snapshot=snapshot;for(const [id,t] of this.tabs){const doc=snapshot.documents.find(d=>d.id===id);if(doc&&!t.dirty&&!t.preset&&doc.hash!==t.baseHash){this.disposeTab(t);this.tabs.delete(id);this.mountTab(doc,t.pinned);}}this.renderTree();this.renderTabs();this.updateTitle();}
  private clear(){if(this.snapshot)for(const [key,url] of draftMediaUrls)if(key.startsWith(this.snapshot.project.id+':')){URL.revokeObjectURL(url);draftMediaUrls.delete(key);}this.contextDispose?.();this.contextDispose=undefined;this.sessionChanged=false;this.inlineDispose?.();for(const t of this.tabs.values())this.disposeTab(t);this.tabs.clear();this.removed.clear();this.moves.clear();this.canvases.replaceChildren();this.active='';this.selected.clear();this.structure=undefined;}
  private disposeTab(t:DocumentTab){t.disposeMedia?.();t.canvas.dispose();t.host.remove();}
  private updateTitle(){this.menu.querySelector('[data-project-title]')!.textContent=this.snapshot?.project.name??'';this.menu.querySelector('[data-session-kind]')!.textContent=this.snapshot&&isTransientProject(this.snapshot.project.id)?'临时会话 · 关闭不保存':'';}
  private documents(){const docs=new Map((this.snapshot?.documents??[]).filter(d=>!['docs/README.md','docs/INDEX.md'].includes(d.path)&&!this.removed.has(d.id)&&!d.path.startsWith('docs/media/')&&!d.id.startsWith('unidentified:')).map(d=>[d.id,d]));for(const [id,t] of this.tabs)if(!t.preset)docs.set(id,t.doc);return [...docs.values()].map(d=>{const move=this.moves.get(d.id);return move?{...d,...move,text:setMetadata(d.text,{system:move.system||undefined,parent:move.parent})}:d;});}
  private projected(){const snapshot=structuredClone(this.snapshot!);snapshot.documents=this.current()?.preset?[this.current()!.doc]:[...new Map([...snapshot.documents.filter(d=>!this.removed.has(d.id)),...this.documents()].map(d=>[d.id,d])).values()];if(this.structure)snapshot.projectEntry={text:this.structure.text,hash:this.structure.baseHash};return snapshot;}
  private groups():KnowledgeGroup[]{return this.structure?parseKnowledge([{path:'PROJECT.md',text:this.structure.text,hash:this.structure.baseHash}]).groups:this.snapshot?.groups??[];}
  openDocument(id:string,pinned=false){
    if(!this.snapshot)return;this.home=false;this.libraryHost.hidden=true;this.work.hidden=false;this.show();
    const doc=this.documents().find(d=>d.id===id);if(!doc)return;
    if(!this.tabs.has(id)){const prior=[...this.tabs.values()].find(t=>!t.pinned&&!t.dirty&&!t.preset);if(prior){this.disposeTab(prior);this.tabs.delete(prior.doc.id);}this.mountTab(doc,pinned);}
    const t=this.tabs.get(id)!;t.pinned ||= pinned;this.recent=[id,...this.recent.filter(value=>value!==id)].slice(0,30);this.saveNavigation();this.active=id;this.renderTabs();t.canvas.refresh();this.renderProperties();this.renderTree();
  }
  private mountTab(doc:ProjectDocument,pinned:boolean,layout?:LayoutCompanion){
    const path=layoutCompanionPath(doc.id),companion=this.snapshot?.companions?.[path];
    if(!layout)try{layout=companion?JSON.parse(companion.text):undefined;}catch{/* 损坏布局保留原文件，服务诊断阻止保存。 */}
    this.canvases.querySelector('.document-empty')?.remove();
    const host=document.createElement('section');host.className='document-tab-content markdown-preview';host.dataset.documentId=doc.id;this.canvases.append(host);
    const tab={doc:{...doc},baseText:doc.hash?doc.text:null,baseHash:doc.hash||null,baseLayoutHash:companion?.hash??null,layout:layout??{format:1,documentId:doc.id,blocks:{}},dirty:false,pinned,host,assets:[]} as unknown as DocumentTab;
    const canvasHost=document.createElement('div');canvasHost.className='document-canvas-host';host.append(canvasHost);
    this.tabs.set(doc.id,tab);
    tab.canvas=new DocumentCanvas(canvasHost,{markdown:doc.text,layout:tab.layout,onInsert:()=>this.insert(),render:text=>projectMarkdown({...tab.doc,text},this.projected(),tab.assets.filter(a=>a.text!==null).map(a=>({path:a.path,text:a.text!}))),onRender:root=>{tab.disposeMedia?.();tab.disposeMedia=mountCreativeBlocks(root,this.projected());},onChange:(text,positions)=>{tab.doc.text=text;tab.layout=positions;const meta=readHeader(text).metadata;tab.doc.title=readHeader(text).body.match(/^#\s+(.+)$/m)?.[1]??tab.doc.title;tab.doc.system=String(meta.system??'');tab.doc.parent=typeof meta.parent==='string'?meta.parent:undefined;tab.doc.color=typeof meta.color==='string'&&/^#[a-f0-9]{6}$/i.test(meta.color)?meta.color:undefined;tab.dirty=true;tab.pinned=true;this.changed(tab);},onEditBlock:(_id,source,done)=>this.editBlock(source,done,tab)});
    this.tabs.set(doc.id,tab);
    host.addEventListener('click',e=>this.moduleClick(e,tab));
    host.addEventListener('dragover',e=>{if(e.dataTransfer?.types.includes(DOCUMENT_DRAG_TYPE)){e.preventDefault();e.dataTransfer.dropEffect='link';}});
    host.addEventListener('drop',e=>{if(!e.dataTransfer?.types.includes(DOCUMENT_DRAG_TYPE))return;e.preventDefault();e.stopPropagation();try{const value=JSON.parse(e.dataTransfer.getData(DOCUMENT_DRAG_TYPE));const target=this.documents().find(d=>d.id===value.documentId||d.id===value.id);if(target){this.documentReference(tab,target);this.notice('已插入文档引用，源文档没有移动。');}}catch{this.notice('无法读取拖入的文档引用。');}});
    return tab;
  }
  private changed(tab:DocumentTab){
    if(!tab.preset&&this.snapshot&&!isTransientProject(this.snapshot.project.id))cacheDraft(this.snapshot.project.id,{id:'desktop-'+tab.doc.id,purpose:'document',documentPath:tab.doc.path,baseHash:tab.baseHash,baseText:tab.baseText,text:tab.doc.text,updatedAt:new Date().toISOString(),companions:[{path:layoutCompanionPath(tab.doc.id),baseHash:tab.baseLayoutHash,text:JSON.stringify(tab.layout)}],assets:tab.assets.map(a=>({path:a.path,text:a.text!,encoding:'base64'}))});
    this.renderTabs();this.notice(tab.preset?'预设有未保存修改。':'文档草稿已保留；保存当前文档不会保存其他标签。');
  }
  private renderTabs(){
    this.contextDispose?.();this.contextDispose=undefined;this.canvases.querySelector('.document-context')?.remove();this.canvases.querySelector('.document-overview')?.remove();
    this.tabbar.innerHTML=[...this.tabs.values()].map(t=>`<div class="document-tab ${t.doc.id===this.active?'active':''} ${!t.pinned?'temporary':''}"><button role="tab" aria-selected="${t.doc.id===this.active}" data-tab="${h(t.doc.id)}">${t.preset?'预设 · ':''}${h(t.doc.title)}${t.dirty?' ●':''}</button><button data-close-tab="${h(t.doc.id)}" aria-label="关闭${h(t.doc.title)}">×</button></div>`).join('');
    this.tabbar.onclick=e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('button');if(b?.dataset.tab){this.active=b.dataset.tab;this.renderTabs();this.current()?.canvas.refresh();this.renderProperties();}if(b?.dataset.closeTab)void this.closeTab(b.dataset.closeTab).catch(err=>this.report(err));};
    this.tabbar.ondblclick=e=>{const id=(e.target as HTMLElement).closest<HTMLElement>('[data-tab]')?.dataset.tab;if(id){this.tabs.get(id)!.pinned=true;this.renderTabs();}};
    for(const [id,t] of this.tabs)t.host.hidden=id!==this.active;
    if(!this.tabs.size)this.canvases.innerHTML='<div class="document-empty"><h2>一份文档，一个自由画布</h2><p>从左侧打开文档，或使用“＋”创建基础文档。角色卡、地图卡和道具卡都可以从文档预设创建。</p></div>';
  }
  private renderTree(){
    const docs=this.documents(),groups=this.groups(),query=this.filter.toLowerCase();
    const match=(d:ProjectDocument)=>{const m=readHeader(d.text).metadata;return !query||`${d.title} ${m.purpose??''} ${JSON.stringify(m.tags??[])}`.toLowerCase().includes(query);};
    const row=(d:ProjectDocument,depth:number):string=>{const children=query||this.navFilter!=='all'?[]:docs.filter(c=>c.parent===d.id);return `<div role="treeitem" tabindex="0" aria-selected="${this.selected.has(d.id)}" draggable="true" data-doc="${h(d.id)}" class="document-tree-row ${this.active===d.id?'active':''}" style="--depth:${depth};--category-color:${this.color(d)}"><button data-fold="doc-${h(d.id)}" ${children.length?'':'disabled'} aria-label="展开或折叠子文档">${children.length?(this.collapsed.has('doc-'+d.id)?'▸':'▾'):'·'}</button><i class="document-color" aria-hidden="true"></i><span>${h(d.title)}${this.tabs.get(d.id)?.dirty?' ●':''}</span><button data-doc-menu="${h(d.id)}" aria-label="文档选项">⋯</button></div>${this.collapsed.has('doc-'+d.id)&&!query?'':children.filter(match).map(c=>row(c,depth+1)).join('')}`;};
    const group=(g:KnowledgeGroup,depth:number):string=>`<div class="document-tree-group" data-category="${h(g.id)}" style="--depth:${depth};--category-color:${categoryColor(g.color)}"><button data-fold="group-${h(g.id)}">${this.collapsed.has('group-'+g.id)?'▸':'▾'} <i class="document-color" aria-hidden="true"></i> ${h(g.label)}</button><button data-category-menu="${h(g.id)}" aria-label="分类选项">⋯</button></div>${this.collapsed.has('group-'+g.id)&&!query?'':groups.filter(c=>c.parent===g.id).map(c=>group(c,depth+1)).join('')+docs.filter(d=>d.system===g.id&&!d.parent&&match(d)).map(d=>row(d,depth+1)).join('')}`;
    this.tree.innerHTML=query||this.navFilter!=='all'?docs.filter(d=>match(d)&&(this.navFilter==='all'||this.navFilter==='favorites'&&this.favorites.has(d.id)||this.navFilter==='recent'&&this.recent.includes(d.id))).map(d=>row({...d,parent:undefined},0)).join(''):groups.filter(g=>!g.parent||!groups.some(p=>p.id===g.parent)).map(g=>group(g,0)).join('')+`<div class="document-tree-group" data-category=""><span>未分类</span></div>`+docs.filter(d=>(!d.system||!groups.some(g=>g.id===d.system))&&(!d.parent||!docs.some(p=>p.id===d.parent))).map(d=>row(d,0)).join('');
    const quick=document.createElement('nav');quick.className='document-quick-access';quick.innerHTML=['all','favorites','recent'].map((id,i)=>'<button data-quick="'+id+'" aria-pressed="'+(this.navFilter===id)+'">'+['全部','收藏','最近'][i]+'</button>').join('');this.tree.prepend(quick);
    quick.onclick=e=>{const id=(e.target as HTMLElement).closest<HTMLElement>('[data-quick]')?.dataset.quick;if(id){e.stopPropagation();this.navFilter=id;this.renderTree();}};
    this.tree.onclick=e=>{const target=e.target as HTMLElement,fold=target.closest<HTMLElement>('[data-fold]'),menu=target.closest<HTMLElement>('[data-doc-menu]'),category=target.closest<HTMLElement>('[data-category-menu]'),line=target.closest<HTMLElement>('[data-doc]');if(fold){const id=fold.dataset.fold!;this.collapsed.has(id)?this.collapsed.delete(id):this.collapsed.add(id);this.saveNavigation();this.renderTree();return;}if(category){this.categoryMenu(category.dataset.categoryMenu!,category);return;}if(!line)return;const id=line.dataset.doc!;if(menu){if(!this.selected.has(id))this.selected=new Set([id]);this.docMenu(id,menu);return;}if(e.shiftKey&&this.lastSelected){const visible=[...this.tree.querySelectorAll<HTMLElement>('[data-doc]')].map(d=>d.dataset.doc!),a=visible.indexOf(this.lastSelected),b=visible.indexOf(id);this.selected=new Set(visible.slice(Math.min(a,b),Math.max(a,b)+1));this.renderTree();return;}if(e.ctrlKey||e.metaKey){this.selected.has(id)?this.selected.delete(id):this.selected.add(id);this.renderTree();return;}this.selected=new Set([id]);this.lastSelected=id;this.openDocument(id);};
    this.tree.ondblclick=e=>{const id=(e.target as HTMLElement).closest<HTMLElement>('[data-doc]')?.dataset.doc;if(id)this.openDocument(id,true);};
    this.tree.oncontextmenu=e=>{const line=(e.target as HTMLElement).closest<HTMLElement>('[data-doc],[data-category]');if(!line)return;e.preventDefault();if(line.dataset.doc){if(!this.selected.has(line.dataset.doc))this.selected=new Set([line.dataset.doc]);this.docMenu(line.dataset.doc,line,e);}else this.categoryMenu(line.dataset.category!,line,e);};
    this.tree.ondragstart=e=>{const id=(e.target as HTMLElement).closest<HTMLElement>('[data-doc]')?.dataset.doc,doc=docs.find(d=>d.id===id);if(!doc||!e.dataTransfer)return;if(!this.selected.has(id!))this.selected=new Set([id!]);e.dataTransfer.setData(DOCUMENT_DRAG_TYPE,JSON.stringify({id,documentId:id,projectId:this.snapshot!.project.id,title:doc.title,path:doc.path}));e.dataTransfer.setData('application/x-cewen-tree-selection',JSON.stringify([...this.selected]));e.dataTransfer.effectAllowed='copyMove';};
    this.tree.ondragover=e=>{if(e.dataTransfer?.types.includes('application/x-cewen-tree-selection')){e.preventDefault();e.dataTransfer.dropEffect='move';}};
    this.tree.ondrop=e=>{e.preventDefault();const line=(e.target as HTMLElement).closest<HTMLElement>('[data-doc],[data-category]');if(!line)return;void this.moveDocuments(line.dataset.category,line.dataset.doc).catch(err=>this.report(err));};
    void this.renderCollections();
  }
  private docMenu(id:string,anchor:HTMLElement,event?:MouseEvent){showAppMenu([{label:'打开并固定标签',run:()=>this.openDocument(id,true)},{label:'卡片关系预览',run:()=>this.graphView(undefined,id)},{label:this.favorites.has(id)?'取消收藏':'收藏文档',run:()=>{this.favorites.has(id)?this.favorites.delete(id):this.favorites.add(id);this.saveNavigation();this.renderTree();}},{label:'复制文档链接',run:()=>navigator.clipboard.writeText(location.origin+location.pathname+'?project='+this.snapshot!.project.id+'#cewen-doc='+encodeURIComponent(id))},{label:'重命名…',shortcut:'F2',run:()=>this.rename(id)},{label:`移动 ${this.selected.size||1} 份文档到…`,run:()=>this.moveDialog()},{label:'加入集合…',run:()=>this.addToCollection()},{label:'在目录中定位',run:()=>this.reveal(id)},{label:'独立复制文档',run:()=>this.duplicate(id)},{label:'保存为文档预设…',run:()=>{this.openDocument(id,true);return this.capturePreset();}},{label:'归档所选文档',separator:true,run:()=>this.archiveSelected()},{label:'删除所选文档…',danger:true,run:()=>this.deleteDocuments()}],anchor,event?{x:event.clientX,y:event.clientY}:undefined);}
  private categoryMenu(id:string,anchor:HTMLElement,event?:MouseEvent){showAppMenu([{label:'在此新建文档',run:()=>this.newDocument(id)},{label:'新建子分类…',run:()=>this.newCategory(id)},{label:'分类卡片视图',run:()=>this.cards(id)},{label:'分类颜色…',disabled:!id,run:()=>this.changeCategoryColor(id)},{label:'重命名分类…',disabled:!id,run:()=>this.renameCategory(id)},{label:'移动分类…',disabled:!id,run:()=>this.moveCategory(id)},{label:'删除分类，保留文档…',disabled:!id,danger:true,run:()=>this.removeCategory(id)}],anchor,event?{x:event.clientX,y:event.clientY}:undefined);}
  private renderProperties(){
    this.inspector.onclick=null;
    this.inlineDispose?.();this.inlineDispose=undefined;const t=this.current();if(!t){this.inspector.innerHTML='<p>选择文档后查看属性。</p>';return;}
    const meta=readHeader(t.doc.text).metadata;
    this.inspector.innerHTML=`<header><h3>${t.preset?'预设属性':'文档属性'}</h3><button data-property-menu aria-label="文档更多操作">⋯</button></header><form><label>名称<input name="title" value="${h(t.doc.title)}" maxlength="200" required/></label><label>用途<input name="purpose" value="${h(meta.purpose)}" placeholder="如角色、地图、道具；可自定义"/></label><label>标签<input name="tags" value="${h(Array.isArray(meta.tags)?meta.tags.join('，'):'')}" placeholder="多个标签用逗号分隔"/></label><label><input type="checkbox" name="inheritColor" ${t.doc.color?'':'checked'}/>继承分类颜色</label><label>文档颜色<input type="color" name="color" value="${h(t.doc.color??this.groups().find(g=>g.id===t.doc.system)?.color??'#94A5BC')}"/></label><label>状态<select name="status">${[['draft','草稿'],['question','待确认'],['confirmed','已确认'],['archived','已归档']].map(([v,label])=>`<option value="${v}" ${meta.status===v?'selected':''}>${label}</option>`).join('')}</select></label><button type="submit">应用到文档草稿</button></form><section><h4>所在位置</h4><p style="--category-color:${this.color(t.doc)}"><i class="document-color" aria-hidden="true"></i> ${h(this.groups().find(g=>g.id===t.doc.system)?.label||'未分类')}</p><button data-move>移动到…</button></section><section><button data-insert>＋ 插入模块</button><button data-ask>围绕本文问策</button><button data-production-prepare>准备素材生产…</button><button data-save>保存当前文档</button></section><details><summary>文件位置</summary><code>${h(t.doc.path)}</code></details>`;
    this.inspector.querySelector('form')!.onsubmit=e=>{e.preventDefault();const data=new FormData(e.currentTarget as HTMLFormElement);t.doc.title=String(data.get('title'));t.doc.status=String(data.get('status')) as ProjectDocument['status'];t.canvas.replace(setTitle(setMetadata(t.doc.text,{purpose:String(data.get('purpose')),tags:String(data.get('tags')).split(/[,，]/).map(s=>s.trim()).filter(Boolean),status:t.doc.status,color:data.has('inheritColor')?undefined:String(data.get('color'))}),t.doc.title));this.renderTree();};
    const properties=this.inspector.querySelector('form')!;
    properties.oninput=e=>{if((e as InputEvent).isComposing)return;properties.dispatchEvent(new Event('submit',{cancelable:true}));};
    properties.addEventListener('compositionend',()=>properties.dispatchEvent(new Event('submit',{cancelable:true})));
    this.inspector.addEventListener('cewen:editor-close',()=>this.renderProperties(),{once:true});
    this.inspector.querySelector('[data-property-menu]')!.addEventListener('click',e=>this.docMenu(t.doc.id,e.currentTarget as HTMLElement));
    this.inspector.querySelector('[data-production-prepare]')?.addEventListener('click',()=>void this.contextual('prepare-production').catch(e=>this.report(e)));this.inspector.querySelector('[data-insert]')!.addEventListener('click',()=>this.insert());this.inspector.querySelector('[data-save]')!.addEventListener('click',()=>void this.save().catch(e=>this.report(e)));this.inspector.querySelector('[data-ask]')!.addEventListener('click',()=>void openCollaboration('inquiry',this.projected(),[t.doc.id]).catch(e=>this.report(e)));this.inspector.querySelector('[data-move]')!.addEventListener('click',()=>{this.selected=new Set([t.doc.id]);void this.moveDialog();});
  }
  private revealInspector(){this.work.classList.remove('hide-properties');if(innerWidth<1000)this.work.classList.add('show-properties');}
  private editBlock(source:string,done:(next:string)=>void,tab:DocumentTab){
    this.revealInspector();this.inlineDispose?.();this.inspector.innerHTML='<header><h3>编辑内容块</h3></header><div class="inline-rich-editor"></div><footer><button data-cancel>返回属性</button><button data-apply>完成编辑</button></footer>';
    const rich=new RichWriting(this.inspector.querySelector('.inline-rich-editor')!,source,next=>done(next.trimEnd()+'\n\n'),async()=>{throw new Error('请使用文档的插入图片入口导入素材。');},url=>url,()=>{});this.inlineDispose=()=>rich.dispose();
    void rich.create().catch(()=>{rich.dispose();const editor=this.inspector.querySelector('.inline-rich-editor');if(editor){editor.innerHTML=`<textarea aria-label="内容块源码" rows="16">${h(source)}</textarea>`;}});
    this.inspector.querySelector('[data-apply]')!.addEventListener('click',()=>{const textarea=this.inspector.querySelector<HTMLTextAreaElement>('.inline-rich-editor>textarea');done((textarea?.value??rich.read()).trimEnd()+'\n\n');this.renderProperties();});
    this.inspector.querySelector('[data-cancel]')!.addEventListener('click',()=>this.renderProperties());
  }
  private moduleClick(event:MouseEvent,tab:DocumentTab){
    const b=(event.target as HTMLElement).closest<HTMLElement>('[data-confirm-decision],[data-object-reference],[data-object-copy],[data-source-document],[data-object-edit],[data-object-open],[data-sequence-play],[data-quest-open],[data-quest-target],[data-production-open],a[href^="#cewen-doc="]');if(!b)return;event.preventDefault();event.stopPropagation();
    if(b instanceof HTMLAnchorElement){this.openDocument(decodeURIComponent(b.hash.slice(11)).split('/')[0],true);return;}
    if(b.dataset.sourceDocument){this.openDocument(b.dataset.sourceDocument,true);return;}
    const index=buildCreativeIndex(this.projected());
    if(b.dataset.objectReference){const object=moduleRegistry.get('reference')!.create('ref-'+crypto.randomUUID(),'共享引用');object.data.objectId=b.dataset.objectReference;tab.canvas.append(objectBlock(object));}
    if(b.dataset.objectCopy){const source=index.objects.find(o=>o.object.id===b.dataset.objectCopy);if(source)tab.canvas.append(objectBlock(cloneCreativeObject(source.object,'object-'+crypto.randomUUID(),()=> 'row-'+crypto.randomUUID())));}
    if(b.dataset.confirmDecision)void this.contextual('confirm-decision',b.dataset.confirmDecision);
    if(b.dataset.objectEdit){const item=index.objects.find(o=>o.object.id===b.dataset.objectEdit);if(!item)return;this.openModule(item.object.id);}
    if(b.dataset.objectOpen){const item=index.objects.find(o=>o.object.id===b.dataset.objectOpen);if(item)this.openDocument(item.documentId,true);}
    if(b.dataset.sequencePlay)void this.contextual('play',b.dataset.sequencePlay);
    if(b.dataset.questOpen||b.dataset.productionOpen)void this.contextual(b.dataset.questOpen?'open-quest':'production',b.dataset.questOpen||b.dataset.productionOpen);
    if(b.dataset.questTarget)void openCollaboration('inquiry',this.projected(),[tab.doc.id]);
  }
  /** 排演、问策与生产作为当前文档的上下文视图，退出回到同一画布。 */
  private async contextual(action:string,objectId?:string){
    const tab=this.current();if(!tab)return;
    if(action!=='play'&&tab.dirty){const choice=await appChoice('先保存所选文档','此操作读取已保存的模块。当前文档需要先保存，其他标签草稿保持独立。',[{id:'save',label:'保存当前文档后继续'},{id:'cancel',label:'返回编辑'}]);if(choice!=='save')return;await this.save();if(this.current()?.dirty)return;}
    this.contextDispose?.();this.canvases.querySelector('.document-context')?.remove();for(const t of this.tabs.values())t.host.hidden=true;
    const panel=document.createElement('section');panel.className='document-context';const back=document.createElement('button');back.textContent='← 返回 '+tab.doc.title;back.onclick=()=>{this.renderTabs();this.renderProperties();};const host=document.createElement('div');panel.append(back,host);this.canvases.append(panel);
    if(action==='play'){const player=new AnimaticPlayer(host,this.projected(),buildCreativeIndex(this.projected()),objectId!);this.contextDispose=()=>player.dispose();return;}
    const workspace=new CreativeWorkspace(host,s=>{this.receive(s);this.options.apply(s);},()=>this.options.proposals(),true);workspace.receive(this.snapshot!);this.contextDispose=()=>workspace.deactivate();await workspace.handle({action,objectId});
    host.addEventListener('click',event=>{const button=(event.target as HTMLElement).closest<HTMLElement>('[data-object-open],[data-object-edit]');if(!button)return;event.stopPropagation();this.renderTabs();this.renderProperties();const item=buildCreativeIndex(this.projected()).objects.find(o=>o.object.id===(button.dataset.objectEdit||button.dataset.objectOpen));if(item){this.openDocument(item.documentId,true);if(button.dataset.objectEdit)this.openModule(item.object.id);}});
  }
  /** 旧书签和模块深链统一定位回拥有它的基础文档。 */
  async handleCreative(detail:{action:string;objectId?:string;documentId?:string}){if(detail.action==='new-project'){await this.newProject();return;}const item=buildCreativeIndex(this.projected()).objects.find(o=>o.object.id===detail.objectId);if(item)this.openDocument(item.documentId,true);else if(detail.documentId)this.openDocument(detail.documentId,true);if(detail.action==='edit'&&item)this.openModule(item.object.id);else if(['play','production','open-quest','confirm-decision'].includes(detail.action))await this.contextual(detail.action,detail.objectId);else if(detail.action==='catalog')this.insert();else if(detail.action==='quest'&&this.current())await openCollaboration('inquiry',this.projected(),[this.current()!.doc.id]);}
  private openModule(id:string){this.revealInspector();
    const snapshot=this.projected(),item=buildCreativeIndex(snapshot).objects.find(o=>o.object.id===id);if(!item)return;
    const tab=this.tabs.get(item.documentId);if(!tab)return;
    if(['production','media'].includes(item.object.type)){this.notice('媒体请重新导入新版本；生产批次通过候选审核操作。');return;}
    this.inlineDispose?.();this.inlineDispose=undefined;this.inspector.onclick=null;
    const update=(object:import('../shared/creative/model').CreativeObject)=>{const current=buildCreativeIndex(this.projected()).objects.find(o=>o.object.id===id);if(!current)return;tab.canvas.replace(tab.doc.text.slice(0,current.start)+objectBlock(object)+tab.doc.text.slice(current.end));};
    const editor=openObjectEditor({object:item.object,index:buildCreativeIndex(snapshot),snapshot,documentId:item.documentId,onSaved:()=>{},host:this.inspector,onWorkingDraft:update,onDraft:object=>{update(object);this.renderProperties();}});
    this.inlineDispose=()=>editor.dispatchEvent(new Event('cewen:dispose'));
  }
  private insert(){this.revealInspector();const tab=this.current();if(!tab)return;this.inlineDispose?.();this.inspector.innerHTML=`<header><h3>插入到当前文档</h3><button data-back>返回属性</button></header><button data-text>文字</button><button data-heading>章节标题</button><button data-image>图片</button><button data-media>音频 / 媒体</button><button data-reference>文档引用</button><div class="insert-module-list">${[...moduleRegistry.values()].filter(m=>!['media','production','document-reference'].includes(m.type)).map(m=>`<button data-module="${h(m.type)}"><strong>${h(m.title)}</strong><small>${h(m.description)}</small></button>`).join('')}</div>`;
    this.inspector.onclick=e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!b)return;if(b.hasAttribute('data-back')){this.inspector.onclick=null;this.renderProperties();}if(b.hasAttribute('data-text')){tab.canvas.append('双击此处编辑文字。');this.renderProperties();}if(b.hasAttribute('data-heading')){tab.canvas.append('## 新章节');this.renderProperties();}if(b.hasAttribute('data-image'))void this.importImage(tab).catch(e=>this.report(e));if(b.hasAttribute('data-media'))void this.importMedia(tab).catch(e=>this.report(e));if(b.hasAttribute('data-reference'))void this.insertReference(tab);if(b.dataset.module){const object=moduleRegistry.get(b.dataset.module)!.create('object-'+crypto.randomUUID());if(object.type==='speech')object.data.text='待填写对白';if(object.type==='quest')object.data.goal='待填写目标';tab.canvas.append(objectBlock(object));this.openModule(object.id);}};
  }
  private chooseFile(accept:string):Promise<File|undefined>{return new Promise(resolve=>{const input=document.createElement('input');input.type='file';input.accept=accept;input.onchange=()=>resolve(input.files?.[0]);input.oncancel=()=>resolve(undefined);input.click();});}
  private async importImage(tab:DocumentTab){const file=await this.chooseFile('image/png,image/jpeg,image/webp,image/gif');if(!file)return;if(file.size>12*1024*1024)throw new Error('图片超过 12 MiB，请先缩小后导入。');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);const extension=file.type==='image/jpeg'?'jpg':file.type.split('/')[1];const path=`docs/assets/image-${crypto.randomUUID()}.${extension}`;tab.assets.push({path,text:btoa(binary),encoding:'base64',baseHash:null});tab.canvas.append(`![${file.name.replace(/[\[\]]/g,'')}](../assets/${path.split('/').at(-1)})`);this.renderProperties();}
  /** 导入仅写当前文档草稿与内存播放地址，用户保存时才登记正式媒体。 */
  private async importMedia(tab:DocumentTab){if(tab.preset){const slot=moduleRegistry.get('reference')!.create('object-'+crypto.randomUUID(),'待选择媒体');tab.canvas.append(objectBlock(slot));this.notice('预设已加入媒体引用占位；创建文档后再选择项目媒体。');return;}const file=await this.chooseFile('audio/*,image/*');if(!file)return;const bytes=new Uint8Array(await file.arrayBuffer()),info=detectMedia(bytes),durationMs=await mediaInput(file);const permission=await appForm('插入媒体草稿','<p>'+h(file.name)+'</p><label>许可或来源<input name="permission" required placeholder="本人创作，仅本项目使用"/></label><p>保存当前文档时才写入项目，放弃草稿不创建素材文件。</p>','插入',data=>String(data.get('permission')));if(!permission)return;const digest=await crypto.subtle.digest('SHA-256',bytes),hash=[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join(''),path='assets/objects/'+hash+'/content.'+info.extension;let text='';for(const byte of bytes)text+=String.fromCharCode(byte);if(!this.snapshot!.media?.[path])tab.assets.push({path,text:btoa(text),encoding:'base64',baseHash:null});draftMediaUrls.set(this.snapshot!.project.id+':'+path,URL.createObjectURL(new Blob([bytes],{type:info.mime})));const existing=buildCreativeIndex(this.projected()).objects.find(o=>o.object.type==='media'&&o.object.data.sha256===hash);if(existing){const ref=moduleRegistry.get('reference')!.create('object-'+crypto.randomUUID(),file.name);ref.data.objectId=existing.object.id;tab.canvas.append(objectBlock(ref));}else tab.canvas.append(objectBlock({schema:1,id:'media-'+hash,type:'media',title:file.name,status:'draft',data:{...info,path,sha256:hash,bytes:bytes.length,durationMs,originalName:file.name,permission}}));this.renderProperties();}
  private documentReference(tab:DocumentTab,source:ProjectDocument){const object=moduleRegistry.get('document-reference')!.create('object-'+crypto.randomUUID(),source.title);object.data.documentId=source.id;tab.canvas.append(objectBlock(object));}
  private outline(){this.revealInspector();const tab=this.current();if(!tab)return;this.inlineDispose?.();this.inspector.onclick=null;this.inspector.innerHTML='<header><h3>当前文档大纲</h3></header>';for(const heading of tab.host.querySelectorAll<HTMLElement>('.document-canvas-content h1,.document-canvas-content h2,.document-canvas-content h3,.document-canvas-content h4')){const button=document.createElement('button');button.textContent=heading.textContent;button.style.marginLeft=(Number(heading.tagName.slice(1))-1)*10+'px';button.onclick=()=>tab.canvas.locate(heading.closest<HTMLElement>('[data-block-id]')!.dataset.blockId!);this.inspector.append(button);}}
  private cards(category?:string){this.inlineDispose?.();this.canvases.querySelector('.document-overview')?.remove();for(const tab of this.tabs.values())tab.host.hidden=true;const overview=document.createElement('section');overview.className='document-overview';const docs=this.documents().filter(d=>category===undefined||d.system===category);overview.innerHTML=`<header><h2>${h(category===undefined?'文档卡片视图':this.groups().find(g=>g.id===category)?.label||'未分类')}</h2><p>${docs.length} 份文档 · 同一份正文</p></header><div>${docs.map(d=>`<button data-card-doc="${h(d.id)}" style="--category-color:${this.color(d)}"><strong>${h(d.title)}</strong><small>${h(readHeader(d.text).metadata.purpose||'基础文档')}</small><span>${h(readHeader(d.text).body.replace(/\x60{3}[\s\S]*?\x60{3}/g,'').replace(/<!--[\s\S]*?-->/g,'').slice(0,150))}</span></button>`).join('')}</div>`;overview.onclick=e=>{const id=(e.target as HTMLElement).closest<HTMLElement>('[data-card-doc]')?.dataset.cardDoc;if(id){overview.remove();this.openDocument(id,true);}};this.canvases.append(overview);}
  private async insertReference(tab:DocumentTab){const id=await appForm('插入文档引用',`<label>源文档<select name="document">${this.documents().filter(d=>d.id!==tab.doc.id).map(d=>`<option value="${h(d.id)}">${h(d.title)}</option>`).join('')}</select></label>`,'插入',data=>String(data.get('document')));const doc=this.documents().find(d=>d.id===id);if(doc)this.documentReference(tab,doc);}
  private async newProject(){if(!await this.leave())return;await projectWizard(s=>this.open(s,true));}
  async newDocument(category=''){if(!this.snapshot)return;this.show();await this.loadPresets();const picked=await pickDocumentPreset(this.allPresets());const result=picked?{name:picked.name,preset:picked.id}:undefined;if(!result)return;const preset=this.allPresets().find(p=>p.id===result.preset),value=preset?instantiateDocumentPreset(preset,result.name):{id:'doc-'+crypto.randomUUID(),markdown:'',layout:undefined,assets:{}};const text=value.markdown||`---\nid: ${value.id}\ntype: dd\nstatus: draft\n---\n\n# ${result.name.replace(/[\r\n]/g,' ')}\n\n双击内容块开始编辑，或插入模块。\n`;const doc:ProjectDocument={id:value.id,title:result.name,type:'dd',status:'draft',system:category,path:`docs/dd/${value.id}.md`,text:setMetadata(text,{system:category||undefined}),hash:''};this.canvases.querySelector('.document-empty')?.remove();const tab=this.mountTab(doc,true,value.layout);tab.assets=Object.entries(value.assets).map(([path,text])=>({path,text,baseHash:null,encoding:'base64'}));tab.dirty=true;this.active=doc.id;this.changed(tab);this.renderTree();this.renderProperties();}
  private changes(tabs:DocumentTab[],includeMoves=false){const changes:FileChange[]=[];if(includeMoves)for(const doc of this.removed.values()){if(doc.hash)changes.push({path:doc.path,text:null,baseHash:doc.hash});const layout=layoutCompanionPath(doc.id),hash=this.snapshot!.companions?.[layout]?.hash;if(hash)changes.push({path:layout,text:null,baseHash:hash});}for(const t of tabs.filter(t=>t.dirty&&!t.preset)){changes.push({path:t.doc.path,text:t.doc.text,baseHash:t.baseHash},{path:layoutCompanionPath(t.doc.id),text:JSON.stringify(t.layout,null,2),baseHash:t.baseLayoutHash},...t.assets.filter(a=>!a.path.startsWith('assets/objects/')));}if(includeMoves)for(const [id,move] of this.moves){const doc=this.snapshot!.documents.find(d=>d.id===id),tab=this.tabs.get(id);const change=changes.find(c=>c.path===(doc?.path??tab?.doc.path));if(change&&change.text)change.text=setMetadata(change.text,{system:move.system||undefined,parent:move.parent});else if(doc)changes.push({path:doc.path,baseHash:doc.hash,text:setMetadata(doc.text,{system:move.system||undefined,parent:move.parent})});}return changes;}
  async save(all=false){
    if(this.busy||!this.snapshot)return;if(this.current()?.preset&&!all){await this.savePreset(this.current()!);return;}
    if(all)for(const t of this.tabs.values())if(t.preset&&t.dirty)await this.savePreset(t);
    if(transientProjects.get(this.snapshot.project.id)==='preset')return;
    if(isTransientProject(this.snapshot.project.id)){await this.saveAs();return;}
    let tabs=(all?[...this.tabs.values()]:this.current()?[this.current()!]:[]).filter(t=>t.dirty&&!t.preset);
    // 只有尚未正式存在的引用目标需要连带保存；已有目标的其他正文草稿保持独立。
    const required=new Set(tabs),projected=this.projected(),index=buildCreativeIndex(projected),savedObjects=new Set(buildCreativeIndex(this.snapshot).objects.map(o=>o.object.id));
    for(let n=0;n<this.tabs.size;n++)for(const t of [...required]){
      for(const ref of index.references.filter(r=>r.path===t.doc.path&&!savedObjects.has(r.targetId))){const target=index.objects.find(o=>o.object.id===ref.targetId),other=target&&this.tabs.get(target.documentId);if(other?.dirty)required.add(other);}
      for(const ref of index.objects.filter(o=>o.documentId===t.doc.id&&o.object.type==='document-reference')){const other=this.tabs.get(String(ref.object.data.documentId));if(other?.dirty&&!other.baseHash)required.add(other);}
      for(const match of t.doc.text.matchAll(/\[[^\]]*\]\(([^)]+)\)/g)){const target=resolveDocumentLink(t.doc.path,match[1]),other=[...this.tabs.values()].find(o=>o.doc.path===target?.path);if(other?.dirty&&!other.baseHash)required.add(other);}
    }
    if(required.size>tabs.length){const added=[...required].filter(t=>!tabs.includes(t));const chosen=await appChoice('保存新引用的来源',`当前文档引用了尚未保存的资料：\n${added.map(t=>t.doc.title).join('、')}\n需要一并保存这些资料，才能形成完整版本。`,[{id:'save',label:'一并保存以上文档'},{id:'cancel',label:'取消，继续编辑'}]);if(chosen!=='save')return;tabs=[...required];}
    let includeMoves=all;
    if(!all&&this.moves.size&&tabs.some(t=>this.moves.has(t.doc.id))){const chosen=await appChoice('保存项目结构草稿',`${this.moves.size} 份文档的归属有共同修改。保存结构不会提交其他标签的正文草稿。`,[{id:'save',label:'一并保存归属修改'},{id:'cancel',label:'取消'}]);if(chosen!=='save')return;includeMoves=true;}
    const changes=this.changes(tabs,includeMoves);
    if(this.structure&&(all||tabs.some(t=>!this.snapshot!.groups.some(g=>g.id===t.doc.system)&&t.doc.system))){if(!all){const chosen=await appChoice('保存所需的分类结构','当前文档使用了尚未保存的分类，需同时保存项目分类结构。其他文档草稿不会提交。',[{id:'save',label:'同时保存分类结构'},{id:'cancel',label:'返回编辑'}]);if(chosen!=='save')return;}changes.push({path:'PROJECT.md',text:this.structure.text,baseHash:this.structure.baseHash});}
    if(!changes.length){this.notice('没有需要保存的修改。');return;}
    this.busy=true;
    try{
      const snapshot=await request<ProjectSnapshot>(`/api/projects/${this.snapshot.project.id}/commit`,{projectId:this.snapshot.project.id,requestId:crypto.randomUUID(),baseRevision:this.snapshot.revision,actor:'user',reason:all?'保存全部文档与项目结构':'保存当前文档',media:tabs.flatMap(t=>t.assets.filter(a=>a.path.startsWith('assets/objects/')).map(a=>({path:a.path,text:a.text!}))),changes});
      let cleanupFailed=false;
      for(const t of tabs){const doc=snapshot.documents.find(d=>d.id===t.doc.id)!;t.doc={...doc};t.baseHash=doc.hash;t.baseText=doc.text;t.baseLayoutHash=snapshot.companions?.[layoutCompanionPath(doc.id)]?.hash??null;t.dirty=false;t.assets=[];try{await deleteDraft(snapshot.project.id,'desktop-'+doc.id);}catch{cleanupFailed=true;}}
      if(includeMoves){this.removed.clear();for(const id of this.moves.keys()){const t=this.tabs.get(id),doc=snapshot.documents.find(d=>d.id===id);if(t&&doc&&!tabs.includes(t)){t.baseHash=doc.hash;t.baseText=doc.text;if(!t.dirty)t.doc={...doc};}}this.moves.clear();}
      if(changes.some(c=>c.path==='PROJECT.md'))this.structure=undefined;
      this.snapshot=snapshot;this.options.apply(snapshot);this.renderTree();this.renderTabs();this.notice(cleanupFailed?'已保存并形成正式版本；旧草稿缓存清理失败，可下次打开时放弃旧草稿。':'已保存并形成正式版本。');
    }catch(error){
      // 冲突时保留工作稿并展示当前磁盘稿；不自动替换保存基准或重试覆盖。
      if(['CONFLICT','FILE_CONFLICT','DEPENDENCY_CHANGED'].includes((error as {code?:string}).code??'')){this.inspector.innerHTML=`<h3>保存冲突 · 工作稿已保留</h3><p>${h((error as Error).message)}</p><p>请核对外部变化。可以先用“项目另存为”保留独立副本。</p>${tabs.map(t=>`<details><summary>${h(t.doc.title)} · 我的草稿</summary><pre>${h(t.doc.text)}</pre></details>`).join('')}`;const current=await request<ProjectSnapshot>(`/api/projects/${this.snapshot.project.id}`);for(const t of tabs){const doc=current.documents.find(d=>d.id===t.doc.id),section=document.createElement('details');section.innerHTML=`<summary>${h(t.doc.title)} · 当前磁盘稿</summary><pre>${h(doc?.text??'文档已被移除')}</pre>`;this.inspector.append(section);}}
      throw error;
    }finally{this.busy=false;}
  }
  async saveAs():Promise<boolean>{
    if(!this.snapshot||this.busy)return false;const library=await listProjects(),old=this.snapshot.project.id,active=this.active,requestId=crypto.randomUUID();
    const next=await appForm('项目另存为',`<label>新项目名称<input name="name" value="${h(this.snapshot.project.name+' · 副本')}" required maxlength="100"/></label><label>保存父目录<input name="directory" value="${h(library.defaultDirectory)}" required/></label><p>包含当前所有文档草稿和分类结构；来源项目保持原样。成功后切换到新项目。</p><label><input type="checkbox" name="preferDrafts"/>遇到来源冲突时，在新副本中采用我的草稿（原文件不变）</label>`,'另存为新项目',async data=>{
      const changes=this.changes([...this.tabs.values()],true);if(this.structure)changes.push({path:'PROJECT.md',text:this.structure.text,baseHash:this.structure.baseHash});
      const content=isTransientProject(old)?await (await import('../browser/transient-projects')).transientContent(old):undefined;
      return request<ProjectSnapshot>('/api/projects/save-as',{name:data.get('name'),directory:data.get('directory'),requestId,preferDrafts:data.has('preferDrafts'),media:[...this.tabs.values()].flatMap(t=>t.assets.filter(a=>a.path.startsWith('assets/objects/')).map(a=>({path:a.path,text:a.text!}))),...(content?{files:content.files,workspaceItems:content.workspaceItems}:{sourceId:old}),changes});
    });if(!next)return false;this.clear();if(isTransientProject(old))(await import('../browser/transient-projects')).disposeTransient(old);this.snapshot=undefined;await this.open(next);if(this.documents().some(d=>d.id===active))this.openDocument(active,true);return true;
  }
  async closeTab(id:string){let tab=this.tabs.get(id);if(!tab)return;if(tab.dirty){const choice=await appChoice('关闭文档',`${tab.doc.title} 有尚未保存的修改。`,[{id:'save',label:'保存后关闭'},{id:'discard',label:'放弃当前草稿'},{id:'cancel',label:'返回编辑'}]);if(!choice||choice==='cancel')return;if(choice==='save'){this.active=id;await this.save();if(this.tabs.get(id)?.dirty)return;}else if(this.snapshot&&!isTransientProject(this.snapshot.project.id))await deleteDraft(this.snapshot.project.id,'desktop-'+id);}tab=this.tabs.get(id);if(!tab)return;this.disposeTab(tab);this.tabs.delete(id);if(this.active===id)this.active=[...this.tabs.keys()].at(-1)??'';this.renderTabs();this.renderProperties();this.renderTree();}
  private async leave():Promise<boolean>{if(!this.snapshot)return true;if(this.hasChanges()){const choice=await appChoice('离开当前项目','有未保存的编辑。示例关闭后会恢复原始内容。',[{id:'save',label:isTransientProject(this.snapshot.project.id)?'另存为新项目':'保存全部'},{id:'discard',label:'放弃本次未保存修改'},{id:'cancel',label:'继续编辑'}]);if(!choice||choice==='cancel')return false;if(choice==='save'){if(isTransientProject(this.snapshot.project.id)){if(!await this.saveAs())return false;}else{await this.save(true);if(this.hasChanges())return false;}}else if(!isTransientProject(this.snapshot.project.id)){for(const t of this.tabs.values())await deleteDraft(this.snapshot.project.id,'desktop-'+t.doc.id);}}return true;}
  async showLibrary(){if(!await this.leave())return;const id=this.snapshot?.project.id;this.clear();this.snapshot=undefined;if(id&&isTransientProject(id))(await import('../browser/transient-projects')).disposeTransient(id);this.home=true;this.work.hidden=true;this.libraryHost.hidden=false;this.updateTitle();this.show();await this.library.refresh();}
  /** 原位改名：Enter 确认，Esc 或离开取消，不阻断其他文档。 */
  private async rename(id=this.active){
    const doc=this.documents().find(d=>d.id===id);if(!doc)return;
    const row=this.tree.querySelector<HTMLElement>('[data-doc="'+CSS.escape(id)+'"]'),label=row?.querySelector('span');
    if(!label){this.openDocument(id,true);this.inspector.querySelector<HTMLInputElement>('[name=title]')?.focus();return;}
    const input=document.createElement('input');input.value=doc.title;input.setAttribute('aria-label','文档新名称');input.maxLength=200;label.replaceWith(input);input.focus();input.select();let done=false;
    const cancel=()=>{if(done)return;done=true;this.renderTree();};
    input.onkeydown=e=>{if(e.isComposing)return;if(e.key==='Escape'){e.preventDefault();e.stopPropagation();cancel();}if(e.key==='Enter'){e.preventDefault();e.stopPropagation();if(!input.value.trim())return;done=true;const title=input.value.trim();this.openDocument(id,true);const tab=this.current()!;tab.doc.title=title;tab.canvas.replace(setTitle(tab.doc.text,title));this.renderTree();this.renderProperties();}};input.onblur=cancel;input.onclick=e=>e.stopPropagation();
  }
  private setGroups(groups:KnowledgeGroup[]){const entry=this.structure??this.snapshot!.projectEntry!;this.structure={text:setMetadata(entry.text,{systems:groups.map(g=>({id:g.id,title:g.label,color:g.color,...(g.parent?{parent:g.parent}:{})}))}),baseHash:'baseHash' in entry?entry.baseHash:entry.hash};this.renderTree();this.notice('分类结构已修改，保存全部后形成正式版本。');}
  /** 分类颜色来自同一 PROJECT.md；浅色主题映射也与原图谱共用。 */
  private color(doc:ProjectDocument){return categoryColor(doc.color??this.groups().find(g=>g.id===doc.system)?.color??'#94A5BC');}
  private async changeCategoryColor(id:string){const group=this.groups().find(g=>g.id===id);if(!group)return;const color=await appForm('分类颜色','<label>颜色<input type="color" name="color" value="'+h(group.color)+'"/></label><p>保存全部后，星空、分类分层、思维导图和关系卡片同步采用此颜色。</p>','应用到结构草稿',data=>String(data.get('color')));if(color)this.setGroups(this.groups().map(g=>g.id===id?{...g,color}:g));}
  private async newCategory(parent?:string){const name=await appForm('新建分类','<label>分类名称<input name="name" required maxlength="80"/></label>','新建',data=>String(data.get('name')));if(name)this.setGroups([...this.groups(),{id:'category-'+crypto.randomUUID(),label:name,color:'#7CBFFF',...(parent?{parent}:{})}]);}
  private reveal(id:string){this.filter='';this.navFilter='all';this.collapsed.clear();this.tree.parentElement!.querySelector<HTMLInputElement>('[type=search]')!.value='';this.renderTree();this.tree.querySelector<HTMLElement>('[data-doc="'+CSS.escape(id)+'"]')?.scrollIntoView({block:'center'});}
  private async duplicate(id:string){const source=this.documents().find(d=>d.id===id);if(!source)return;const tab=this.tabs.get(id),preset=captureDocumentPreset(source.text,source.title+' · 副本',true,tab?.layout);const value=instantiateDocumentPreset(preset);const doc={...source,id:value.id,path:'docs/dd/'+value.id+'.md',title:preset.name,text:setMetadata(value.markdown,{system:source.system,parent:source.parent}),hash:''};const created=this.mountTab(doc,true,value.layout);created.dirty=true;this.active=doc.id;this.changed(created);this.renderTree();this.renderProperties();}
  private async moveCategory(id:string){const groups=this.groups(),descendants=new Set([id]);for(let i=0;i<groups.length;i++)for(const g of groups)if(g.parent&&descendants.has(g.parent))descendants.add(g.id);const parent=await appForm('移动分类','<label>目标父分类<select name="parent"><option value="">顶层</option>'+groups.filter(g=>!descendants.has(g.id)).map(g=>'<option value="'+h(g.id)+'">'+h(g.label)+'</option>').join('')+'</select></label><p>文档归属不变，整个子分类树随之移动。</p>','移动',data=>String(data.get('parent')));if(parent!==undefined)this.setGroups(groups.map(g=>g.id===id?{...g,parent:parent||undefined}:g));}
  private async removeCategory(id:string){const group=this.groups().find(g=>g.id===id);if(!group)return;const answer=await appChoice('删除分类','分类内文档和子分类会移到上一层，正文及引用保留。',[{id:'cancel',label:'取消'},{id:'remove',label:'删除分类并保留资料'}]);if(answer!=='remove')return;for(const doc of this.documents().filter(d=>d.system===id))this.moves.set(doc.id,{system:group.parent??'',parent:doc.parent});this.setGroups(this.groups().filter(g=>g.id!==id).map(g=>g.parent===id?{...g,parent:group.parent}:g));}
  private async renameCategory(id:string){const g=this.groups().find(g=>g.id===id);if(!g)return;const name=await appForm('重命名分类',`<label>名称<input name="name" required value="${h(g.label)}"/></label>`,'更新',data=>String(data.get('name')));if(name)this.setGroups(this.groups().map(g=>g.id===id?{...g,label:name}:g));}
  private async moveDialog(){const result=await appForm('移动文档',`<p>主归属只有一个。移动时会包含所选文档的后代。</p><label>目标分类<select name="category"><option value="">未分类</option>${this.groups().map(g=>`<option value="${h(g.id)}">${h(g.label)}</option>`).join('')}</select></label><label>作为子文档（可选）<select name="parent"><option value="">直接位于分类下</option>${this.documents().filter(d=>!this.selected.has(d.id)).map(d=>`<option value="${h(d.id)}">${h(d.title)}</option>`).join('')}</select></label>`,'查看移动范围',data=>({category:String(data.get('category')),parent:String(data.get('parent'))}));if(result)await this.moveDocuments(result.category,result.parent||undefined);}
  private async moveDocuments(category?:string,parent?:string){const docs=this.documents(),ids=new Set(this.selected);for(let i=0;i<docs.length;i++)for(const d of docs)if(d.parent&&ids.has(d.parent))ids.add(d.id);if(parent&&ids.has(parent))throw new Error('不能移动到自身或后代文档。');if(parent)category=docs.find(d=>d.id===parent)?.system??'';const names=docs.filter(d=>ids.has(d.id));const confirm=await appChoice('确认移动范围',`${names.map(d=>d.title).join('、')}\n共 ${names.length} 份文档 → ${parent?docs.find(d=>d.id===parent)?.title:this.groups().find(g=>g.id===category)?.label||'未分类'}`,[{id:'move',label:'更新这些文档的草稿'},{id:'cancel',label:'取消'}]);if(confirm!=='move')return;for(const doc of names){let tab=this.tabs.get(doc.id);if(!tab)tab=this.mountTab(doc,true);const nextParent=doc.parent&&ids.has(doc.parent)?doc.parent:parent;this.moves.set(doc.id,{system:category??'',parent:nextParent});const dirty=tab.dirty;tab.canvas.replace(setMetadata(tab.doc.text,{system:category||undefined,parent:nextParent}));tab.dirty=dirty;if(!dirty&&this.snapshot&&!isTransientProject(this.snapshot.project.id))await deleteDraft(this.snapshot.project.id,'desktop-'+doc.id);}this.renderTree();this.renderProperties();}
  /** 文档删除先进入项目结构草稿；正式保存仍受引用完整性与哈希冲突检查。 */
  private async deleteDocuments(){const docs=this.documents(),ids=new Set(this.selected);for(let i=0;i<docs.length;i++)for(const doc of docs)if(doc.parent&&ids.has(doc.parent))ids.add(doc.id);const selected=docs.filter(d=>ids.has(d.id));if(!selected.length)return;const result=await appChoice('删除文档草稿',selected.map(d=>d.title).join('、')+'\n保存全部后才删除公开文件。历史版本仍保留；若还有引用，需要先处理来源文档。',[{id:'cancel',label:'取消'},{id:'delete',label:'将这些文档标记为删除'}]);if(result!=='delete')return;for(const doc of selected){const original=this.snapshot!.documents.find(d=>d.id===doc.id);if(original)this.removed.set(doc.id,original);const tab=this.tabs.get(doc.id);if(tab)this.disposeTab(tab);this.tabs.delete(doc.id);this.moves.delete(doc.id);if(!isTransientProject(this.snapshot!.project.id))await deleteDraft(this.snapshot!.project.id,'desktop-'+doc.id);}this.active=[...this.tabs.keys()].at(-1)??'';this.selected.clear();this.renderTabs();this.renderProperties();this.renderTree();this.notice('删除已加入项目结构草稿，请保存全部；关闭项目可放弃。');}
  private async archiveSelected(){for(const id of this.selected){const doc=this.documents().find(d=>d.id===id);if(!doc)continue;const tab=this.tabs.get(id)??this.mountTab(doc,true);tab.doc.status='archived';tab.canvas.replace(setMetadata(tab.doc.text,{status:'archived'}));}this.renderTree();}
  private async recoverDrafts(){if(!this.snapshot||isTransientProject(this.snapshot.project.id))return;const id=this.snapshot.project.id,drafts=(await projectDrafts(id)).filter(d=>d.id.startsWith('desktop-'));if(!drafts.length)return;const answer=await appChoice('发现未保存的文档草稿',`${drafts.length} 份草稿。正式文档不会被覆盖，恢复后仍需要保存。`,[{id:'recover',label:'恢复到标签页'},{id:'discard',label:'放弃这些旧草稿'},{id:'later',label:'暂不处理'}]);if(this.snapshot?.project.id!==id)return;if(answer==='discard'){for(const d of drafts)await deleteDraft(id,d.id);}if(answer!=='recover')return;for(const d of drafts){const meta=readHeader(d.text).metadata,doc=this.documents().find(v=>v.path===d.documentPath)??{id:String(meta.id),title:'恢复文档',type:'dd' as const,status:'draft' as const,system:String(meta.system??''),text:d.text,path:d.documentPath,hash:''};this.openDocument(doc.id,true);const t=this.tabs.get(doc.id)??this.mountTab(doc,true);t.baseHash=d.baseHash;t.baseText=d.baseText;const companion=d.companions?.find(c=>c.path===layoutCompanionPath(doc.id));t.baseLayoutHash=companion?.baseHash??t.baseLayoutHash;t.assets=(d.assets??[]).map(a=>({...a,baseHash:null}));for(const asset of t.assets.filter(a=>a.path.startsWith('assets/objects/'))){const bytes=Uint8Array.from(atob(asset.text!),c=>c.charCodeAt(0));draftMediaUrls.set(id+':'+asset.path,URL.createObjectURL(new Blob([bytes],{type:detectMedia(bytes).mime})));}t.canvas.replace(d.text,companion?.text?JSON.parse(companion.text):t.layout);}this.renderTree();}
  private async loadPresets(){this.users=await request<DocumentPreset[]>('/api/document-presets');}
  private allPresets(){return [...builtinDocumentPresets,...this.users].sort((a,b)=>Number(!!b.pinned)-Number(!!a.pinned));}
  /** 从正文采集预设时，实例文字和图片均由用户显式选择，默认只取结构。 */
  private async capturePreset(){
    if(!this.current())return;
    if(this.snapshot&&isTransientProject(this.snapshot.project.id)&&transientProjects.get(this.snapshot.project.id)==='example'&&!await this.saveAs())return;
    const tab=this.current();if(!tab)return;
    const imagePaths=[...new Set([...tab.doc.text.matchAll(/!\[[^\]]*\]\(([^)]+)\)/g)].map(m=>resolveDocumentLink(tab.doc.path,m[1])?.path).filter((p):p is string=>!!p&&p.startsWith('docs/assets/')))];
    const result=await appForm('保存为文档预设',`<label>预设名称<input name="name" value="${h(tab.doc.title)}" required maxlength="100"/></label><label><input type="checkbox" name="content"/>保留示范文字和字段值（默认仅保存结构）</label><fieldset><legend>明确纳入的图片附件</legend>${imagePaths.map(path=>`<label><input type="checkbox" name="asset" value="${h(path)}"/>${h(path)}</label>`).join('')||'<p>没有可纳入的图片附件。</p>'}</fieldset><p>其他外部引用成为占位。不复制凭证、历史或恢复草稿。</p>`,'保存预设',async data=>{
      const selected=new Set(data.getAll('asset').map(String)),assets:Record<string,string>={};
      for(const path of selected){const draft=tab.assets.find(a=>a.path===path);if(draft?.text){assets[path]=draft.text;continue;}const response=await fetch(projectAssetUrl(this.snapshot!,path));if(!response.ok)throw new Error('图片读取失败：'+path);const bytes=new Uint8Array(await response.arrayBuffer());if(bytes.length>12*1024*1024)throw new Error('图片超过预设附件限制：'+path);let text='';for(const byte of bytes)text+=String.fromCharCode(byte);assets[path]=btoa(text);}
      const source=tab.doc.text.replace(/!\[([^\]]*)\]\(([^)]+)\)/g,(match,label,url)=>selected.has(resolveDocumentLink(tab.doc.path,url)?.path??'')?match:'待选择图片：'+label);
      const preset=captureDocumentPreset(source,String(data.get('name')),data.has('content'),tab.layout,selected.size>0);preset.assets=assets;
      return request<DocumentPreset[]>('/api/document-presets',{preset});
    });if(result){this.users=result;this.notice('已保存到我的文档预设，现有文档不会随预设改变。');}
  }

  async presetLibrary(){await this.loadPresets();const chosen=await pickDocumentPreset(this.allPresets(),true);if(!chosen)return;if(this.snapshot&&transientProjects.get(this.snapshot.project.id)==='example'&&!await this.saveAs())return;let preset=this.allPresets().find(p=>p.id===chosen.id)!;if(chosen.action==='delete'){if(preset.source!=='user')throw new Error('官方预设不能删除。');const ok=await appChoice('删除我的预设','已用此预设创建的文档会保留。',[{id:'keep',label:'保留'},{id:'delete',label:'删除预设'}]);if(ok==='delete')this.users=await request<DocumentPreset[]>('/api/document-presets',{remove:preset.id});return;}if(chosen.action==='pin'){if(preset.source==='builtin')preset={...preset,id:'user-'+crypto.randomUUID(),source:'user'};await request('/api/document-presets',{preset:{...preset,pinned:!preset.pinned}});return;}
    if(!this.snapshot){const snapshot=await (await import('../browser/transient-projects')).createTransient('文档预设编辑','preset');await this.open(snapshot);}
    if(chosen.action==='blank')preset={format:1,id:'user-'+crypto.randomUUID(),name:'新预设',description:'',purpose:'',tags:[],source:'user',markdown:'---\nid: preset-blank\ntype: dd\nstatus: draft\n---\n\n# 新预设\n\n在这里组合模块。\n'};
    else if(preset.source==='builtin'||chosen.action==='copy')preset={...structuredClone(preset),id:'user-'+crypto.randomUUID(),source:'user',name:preset.name+' · 我的预设'};
    this.show();const value=instantiateDocumentPreset(preset,preset.name),doc:ProjectDocument={id:value.id,path:`docs/dd/${value.id}.md`,title:preset.name,type:'dd',status:'draft',system:'',text:value.markdown,hash:''};this.canvases.querySelector('.document-empty')?.remove();const t=this.mountTab(doc,true,value.layout);t.preset=preset;t.dirty=true;this.active=doc.id;t.assets=Object.entries(value.assets).map(([path,text])=>({path,text,baseHash:null,encoding:'base64'}));this.renderTabs();t.canvas.refresh();this.renderProperties();
  }
  private async savePreset(tab:DocumentTab){if(this.snapshot&&transientProjects.get(this.snapshot.project.id)==='example')throw new Error('请先将学习示例另存为正式项目，再保存个人预设。');const preset={...tab.preset!,assets:Object.fromEntries(tab.assets.filter(a=>a.text!==null).map(a=>[a.path,a.text!])),name:tab.doc.title,markdown:tab.doc.text,layout:tab.layout,purpose:String(readHeader(tab.doc.text).metadata.purpose??''),tags:readHeader(tab.doc.text).metadata.tags as string[]??[],updatedAt:new Date().toISOString()};this.users=await request<DocumentPreset[]>('/api/document-presets',{preset});tab.preset=preset;tab.dirty=false;this.renderTabs();this.notice('文档预设已保存，现有文档未改变。');}
  async examples(){if(!await this.leave())return;const chosen=await appForm('示例与新手教程','<p>打开后在正常工作台中自由编辑。所有编辑仅存本次会话，关闭后恢复原样。</p><label>学习内容<select name="example"><option value="documents">入门：文档、分类与引用</option><option value="cards">基础文档预设：角色与道具</option><option value="maps">地图：共享底图与局部覆盖层</option><option value="game">游戏：雾港来信</option><option value="narrative">世界观：雾港来信</option><option value="screenplay">剧本：雨夜候车室</option><option value="film">短片：最后一盏灯</option><option value="mixed">进阶：综合虚构工程</option></select></label>','打开示例',data=>String(data.get('example')));if(!chosen)return;const {createLearningExample}=await import('../browser/learning-examples');const snapshot=await createLearningExample(chosen);await this.open(snapshot,true);}
  private async renderCollections(){if(!this.snapshot||this.home)return;const id=this.snapshot.project.id;try{const state=await projectAction<import('../shared/model').WorkspaceState>(id,'workspace');if(this.snapshot?.project.id!==id||!this.tree.isConnected)return;this.tree.querySelector('.document-collections')?.remove();const host=document.createElement('section');host.className='document-collections';host.innerHTML='<h4>集合 · 引用，不改变归属</h4>'+state.items.filter(i=>i.kind==='collection').map(i=>`<details><summary>${h(i.title)}</summary>${i.targets.map(target=>this.documents().find(d=>d.id===target)).filter((d):d is ProjectDocument=>!!d).map(d=>`<button data-collection-doc="${h(d.id)}">${h(d.title)}</button>`).join('')}</details>`).join('');host.onclick=e=>{const id=(e.target as HTMLElement).closest<HTMLElement>('[data-collection-doc]')?.dataset.collectionDoc;if(id)this.openDocument(id,true);};this.tree.append(host);}catch(e){this.report(e);}}
  private async createCollection(){const title=await appForm('新建集合','<label>集合名称<input name="name" required/></label><p>集合保存文档引用，不移动原文档。</p>','创建',data=>String(data.get('name')));if(!title||!this.snapshot)return;const state=await projectAction<import('../shared/model').WorkspaceState>(this.snapshot.project.id,'workspace'),now=new Date().toISOString();await projectAction(this.snapshot.project.id,'workspace',{baseRevision:state.revision,item:{id:'collection-'+crypto.randomUUID(),kind:'collection',title,scope:'personal',targets:[...this.selected],text:'',tags:[],state:'active',createdAt:now,updatedAt:now}});this.renderTree();}
  private async addToCollection(){if(!this.snapshot)return;const state=await projectAction<import('../shared/model').WorkspaceState>(this.snapshot.project.id,'workspace'),collections=state.items.filter(i=>i.kind==='collection');if(!collections.length){await this.createCollection();return;}const id=await appForm('加入集合',`<label>集合<select name="id">${collections.map(i=>`<option value="${h(i.id)}">${h(i.title)}</option>`).join('')}</select></label>`,'加入',data=>String(data.get('id')));const item=collections.find(i=>i.id===id);if(item){await projectAction(this.snapshot.project.id,'workspace',{baseRevision:state.revision,item:{...item,targets:[...new Set([...item.targets,...this.selected])],updatedAt:new Date().toISOString()}});this.renderTree();}}
  private async about(){await appForm('关于策问 Designform',`<p>版本：<strong>${APP_VERSION}</strong></p><p>作者：BAIGE</p><p><a href="https://github.com/Syurli/Designform" target="_blank" rel="noreferrer">GitHub · Syurli/Designform</a></p><p><a href="https://syurli.github.io/Designform/" target="_blank" rel="noreferrer">项目网页与使用入口</a></p><p>以基础文档与自由画布组织创作，按需要组合模块。</p>`,'关闭',()=>true);}
  private key(e:KeyboardEvent){if(e.isComposing||document.querySelector('dialog:modal'))return;const input=(e.target as HTMLElement).closest('input,textarea,select,[contenteditable=true]');if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='o'){e.preventDefault();void this.showLibrary().then(()=>this.libraryHost.querySelector<HTMLButtonElement>('[data-open]')?.click());}if(!input&&(e.ctrlKey||e.metaKey)&&['z','y'].includes(e.key.toLowerCase())){e.preventDefault();if(e.key.toLowerCase()==='y'||e.shiftKey)this.current()?.canvas.redo();else this.current()?.canvas.undo();}if(e.key==='F2'&&!input){e.preventDefault();void this.rename([...this.selected][0]??this.active);}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();e.stopPropagation();void(e.shiftKey?this.saveAs():this.save(e.altKey)).catch(err=>this.report(err));}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='w'){e.preventDefault();void this.closeTab(this.active);}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='n'){e.preventDefault();void(e.shiftKey||this.home?this.newProject():this.newDocument());}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'){e.preventDefault();if(e.shiftKey)this.tree.parentElement!.querySelector<HTMLInputElement>('[type=search]')?.focus();else void appForm('查找当前文档','<label>文字<input name="query" required/></label>','定位',data=>{if(!this.current()?.canvas.find(String(data.get('query'))))throw new Error('当前文档中没有找到这段文字。');return true;});}if(e.key==='ContextMenu'||e.shiftKey&&e.key==='F10'){e.preventDefault();const id=[...this.selected][0]??this.active,anchor=this.tree.querySelector<HTMLElement>('[data-doc="'+CSS.escape(id)+'"]');if(anchor)this.docMenu(id,anchor);}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'&&this.current()){e.preventDefault();void this.insertReference(this.current()!);}}
}
