import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { moduleCatalog } from '../shared/creative/registry.ts';
interface Client {request<T=unknown>(route:string,input?:unknown):Promise<T>}
/** 新工具只开放业务意图；不存在通用 HTTP 代理、用户代答或自我采纳。 */
export function registerCreativeTools(server:McpServer,client:Client){
 const id=z.string().regex(/^[A-Za-z0-9_-]{1,120}$/),requestId=z.string().min(1).max(180),hash=z.string().regex(/^[a-f0-9]{64}$/),ids=z.array(id).max(200).default([]);
 const result=async(action:()=>Promise<unknown>)=>{try{const data=await action(),text=JSON.stringify(data);if(Buffer.byteLength(text)>4*1024*1024)throw new Error('结果超过 4 MiB，请缩小范围；未静默截断');return {content:[{type:'text' as const,text}]};}catch(e){return {isError:true,content:[{type:'text' as const,text:JSON.stringify({error:{code:(e as {code?:string}).code??'CREATIVE_ERROR',message:(e as Error).message}})}]};}};
 const call=(projectId:string,action:string,input:Record<string,unknown>)=>client.request(`/api/projects/${projectId}/creative`,{...input,action});
 server.registerTool('cewen_capabilities',{description:'读取实际版本、全部创作模块及权限边界。预设不限制模块；心跳不表示自动生成。',annotations:{readOnlyHint:true}},()=>result(()=>client.request('/api/creative-capabilities')));
 server.registerTool('cewen_objects',{description:'分页搜索跨文档共享对象。只读公开内容，不返回私人工作区。',inputSchema:{projectId:id,type:z.string().default(''),status:z.string().default(''),tag:z.string().max(200).default(''),relatedId:id.optional(),questId:id.optional(),missingMedia:z.boolean().default(false),query:z.string().max(1000).default(''),offset:z.number().int().min(0).default(0),limit:z.number().int().min(1).max(100).default(40)},annotations:{readOnlyHint:true}},({projectId,...input})=>result(()=>call(projectId,'objects',input)));
 server.registerTool('cewen_object_read',{description:'读取一个对象、所属文档与双层哈希。引用不是副本；修改用通用提案并保留未知字段。',inputSchema:{projectId:id,objectId:id},annotations:{readOnlyHint:true}},({projectId,...input})=>result(()=>call(projectId,'read-object',input)));
 server.registerTool('cewen_object_context',{description:'读取选定对象及其显式依赖，预算不足时报错。媒体仅返回引用元数据，需看图或听音频时另外读取。',inputSchema:{projectId:id,objectIds:ids,budget:z.number().int().min(1000).max(200000).default(100000)},annotations:{readOnlyHint:true}},({projectId,...input})=>result(()=>call(projectId,'context',input)));
 server.registerTool('cewen_quests',{description:'列出项目 Quest。独立问题仍通过原文档工具读取。',inputSchema:{projectId:id,offset:z.number().int().min(0).default(0)},annotations:{readOnlyHint:true}},({projectId,...input})=>result(()=>call(projectId,'objects',{...input,type:'quest'})));
 server.registerTool('cewen_quest_create',{description:'围绕用户明确的目标创建公开 Quest。只建立任务，不生成用户答案或批准决定。',inputSchema:{projectId:id,requestId,questId:id,title:z.string().min(1).max(200),goal:z.string().min(1).max(20000),scope:z.string().max(20000).default(''),targetIds:ids,documentIds:ids}},({projectId,documentIds,...input})=>result(()=>call(projectId,'quest-create',{...input,documentIds:documentIds.join(',')})));
 server.registerTool('cewen_quest_read',{description:'读取 Quest 轮次、真实原始回答、提案与逐目标落实状态。已回答不等于已决定或已落实。',inputSchema:{projectId:id,questId:id},annotations:{readOnlyHint:true}},({projectId,...input})=>result(()=>call(projectId,'quest-read',input)));
 server.registerTool('cewen_quest_events',{description:'从真实修订游标扫描最多25个版本，返回固定游标边界的变更正文、删除路径与最新状态摘要（不重复发送全部回答）。游标失效要重读，不无限轮询。',inputSchema:{projectId:id,questId:id,cursor:z.string().default('')},annotations:{readOnlyHint:true}},({projectId,...input})=>result(()=>call(projectId,'quest-events',input)));
 server.registerTool('cewen_quest_round',{description:'向公开 Quest 原子追加一轮分析与1～30个问题，建议每轮3～5题。保持requestId用于原请求重试；不得代填答案。',inputSchema:{projectId:id,requestId,questId:id,baseHash:hash,roundId:id,summary:z.string().max(20000).default(''),dependencies:z.record(z.string(),hash).default({}),questions:z.array(z.object({id,title:z.string().min(1).max(200),background:z.string().min(1).max(20000),options:z.array(z.string().max(4000)).max(26),mode:z.enum(['single','multiple']).default('single'),targetIds:ids,follows:id.optional(),condition:z.string().optional(),when:z.object({questionId:id,option:z.string().max(4000).optional()}).optional()})).min(1).max(30)}},({projectId,...input})=>result(()=>call(projectId,'quest-round',input)));
 server.registerTool('cewen_production_preview',{description:'只准备图片/配音任务预览，不提交外部模型、不计费，不改变正式内容。返回提示词、任务身份和依赖基准。',inputSchema:{projectId:id,batchId:id,targetIds:z.array(id).min(1).max(100),scope:z.enum(['all','missing','changed']).default('all')},annotations:{readOnlyHint:true}},({projectId,...input})=>result(()=>call(projectId,'production-preview',input)));
 server.registerTool('cewen_production_read',{description:'读取固定生产批次、候选与过期状态。回导不表示采用，采用须由用户操作。',inputSchema:{projectId:id,batchId:id},annotations:{readOnlyHint:true}},({projectId,...input})=>result(()=>call(projectId,'production-read',input)));
 server.registerTool('cewen_media',{description:'读取公开媒体版本的元数据；includeContent=true时返回图片/音频内容（最多5MiB）。不访问任意磁盘路径。',inputSchema:{projectId:id,mediaId:id,includeContent:z.boolean().default(false)},annotations:{readOnlyHint:true}},async({projectId,...input})=>{try{const media=await call(projectId,'media-read',input) as {mime:string;data?:string;[key:string]:unknown};const {data,...metadata}=media;return {content:[{type:'text' as const,text:JSON.stringify(metadata)},...(data?[{type:media.mime.startsWith('audio/')?'audio' as const:'image' as const,data,mimeType:media.mime}]:[])]};}catch(e){return {isError:true,content:[{type:'text' as const,text:(e as Error).message}]};}});
 server.registerResource('creative-modules','cewen://schemas/modules',{description:'所有预设共用的模块字段与 schema；不携带项目内容。',mimeType:'application/json'},async uri=>({contents:[{uri:uri.href,mimeType:'application/json',text:JSON.stringify({schema:1,projectFormat:2,modules:moduleCatalog()})}]}));
 server.registerPrompt('continue-quest',{description:'接续一个明确的创作 Quest；工具是否存在以当前客户端能力为准。',argsSchema:{projectId:id,questId:id}},async({projectId,questId})=>({messages:[{role:'user',content:{type:'text',text:`请继续项目 ${projectId} 的 Quest ${questId}。先用 cewen_quest_read 核对实际回答与修订，再按需读取对象依赖。每轮提出少量关键问题，通过 cewen_quest_round 追加；不代答、不自行采纳。用户提交答案后再次读取，不假装客户端能自动唤醒模型。`}}]}));
}
