import type { ProjectSnapshot } from '../../shared/model';
import { asData,asNumber,asRows,asString,asStrings,type CreativeObject,type CreativeIndex,type ModuleField,type Value,type Data } from '../../shared/creative/model';
import { moduleRegistry,validateObject } from '../../shared/creative/registry';
import { creativeAction } from '../project-client';
import { h } from './render';
import { mountMapEditor } from './map-editor';
export interface EditorOptions {object:CreativeObject;index:CreativeIndex;snapshot:ProjectSnapshot;documentId?:string;isNew?:boolean;onSaved:(snapshot:ProjectSnapshot)=>void}
/** 表单仅局部改写当前模块；原始 Markdown 无关段落与扩展字段全部保留。 */
export function openObjectEditor(options:EditorOptions) {
 const value=structuredClone(options.object),dialog=document.createElement('dialog');dialog.className='project-dialog creative-editor';let dirty=false,busy=false;let disposeSpecial:(()=>void)|undefined;const requestId=crypto.randomUUID(),newDocumentId='doc-'+crypto.randomUUID();
 const definition=moduleRegistry.get(value.type);if(!definition||['production','media'].includes(value.type))throw new Error('本模块由专用工作流管理');
 const storageKey=`cewen-object-draft:${options.snapshot.project.id}:${value.id}`,base=options.index.objects.find(x=>x.object.id===value.id)?.hash??'';
 try{const raw=JSON.parse(localStorage.getItem(storageKey)??'null');if(raw?.base===base&&raw.object?.id===value.id)Object.assign(value,raw.object);}catch{}
 const ordinary=options.snapshot.documents.filter(d=>d.type!=='question'&&!d.path.startsWith('docs/media/')&&!d.path.startsWith('docs/production/')&&!d.path.startsWith('docs/quests/'));
 const get=(path:string)=>path.split('.').reduce<unknown>((o,k)=>(o as Record<string,unknown>)?.[k],value.data);
 const set=(path:string,v:unknown)=>{const parts=path.split('.'),last=parts.pop()!;let at:unknown=value.data;for(const k of parts)at=(at as Record<string,unknown>)[k];(at as Record<string,unknown>)[last]=v;};
 const input=(f:ModuleField,path:string,v:unknown):string=>{
  const attrs=`data-field="${h(path)}" data-kind="${h(f.kind)}" ${f.required?'required':''}`;
  if(f.kind==='rows')return `<fieldset class="creative-rows"><legend>${h(f.label)}</legend>${asRows(v).map((row,i)=>`<details open><summary>${h(row.id)} <button type="button" data-row-move="${h(path)}:${i}:-1">↑</button><button type="button" data-row-move="${h(path)}:${i}:1">↓</button><button type="button" data-row-delete="${h(path)}:${i}">移除</button></summary><div class="creative-fields">${(f.fields??[]).map(sf=>field(sf,`${path}.${i}.${sf.key}`,row[sf.key])).join('')}</div></details>`).join('')}<button type="button" data-row-add="${h(path)}">＋ 添加一行</button></fieldset>`;
  if(f.kind==='object'||f.kind==='objects') {const current=f.kind==='objects'?asStrings(v):[asString(v)];return `<select ${attrs} ${f.kind==='objects'?'multiple size="4"':''}><option value="">未指定</option>${options.index.objects.filter(x=>!f.objectType||x.object.type===f.objectType).map(x=>`<option value="${h(x.object.id)}" ${current.includes(x.object.id)?'selected':''}>${h(x.object.title)} · ${h(x.object.type)} · ${h(x.object.id.slice(-12))}</option>`).join('')}</select>`;}
  if(f.kind==='longtext')return `<textarea ${attrs} rows="3">${h(v)}</textarea>`;
  if(f.kind==='select')return `<select ${attrs}>${f.options?.map(o=>`<option ${o===v?'selected':''}>${h(o)}</option>`).join('')}</select>`;
  return `<input ${attrs} type="${f.kind==='number'?'number':'text'}" value="${h(v??(f.kind==='number'?0:''))}" ${f.kind==='number'?`min="${f.min??0}" max="${f.max??86400000}" step="${f.max===1?0.001:1}"`:''}/>`;
 };
 const field=(f:ModuleField,path:string,v:unknown):string=>f.kind==='rows'?input(f,path,v):`<label>${h(f.label)}${input(f,path,v)}${f.help?`<small>${h(f.help)}</small>`:''}</label>`;
 function render(){disposeSpecial?.();const chosen=dialog.querySelector<HTMLSelectElement>('[name=document]')?.value??options.documentId??'';dialog.innerHTML=`<header class="project-dialog-header"><div><span class="eyebrow">ALL MODULES · 所有项目通用</span><h1>${options.isNew?'插入':'编辑'}${h(definition!.title)}</h1><p>${h(definition!.description)}</p></div><button type="button" data-close aria-label="关闭">×</button></header><form><label>标题<input name="title" value="${h(value.title)}" required maxlength="200"/></label><label>拥有此对象的文档<select name="document" ${options.isNew?'':'disabled'}><option value="">创建独立文档</option>${ordinary.map(d=>`<option value="${h(d.id)}" ${chosen===d.id?'selected':''}>${h(d.title)}</option>`).join('')}</select></label><p class="creative-note">编辑源对象会影响其所有实时引用；使用“独立复制”才能断开共享。此表单不会直接保存未选文档。</p><div data-special-editor></div><div class="creative-fields">${definition!.fields.map(f=>field(f,f.key,value.data[f.key])).join('')}</div><details><summary>稳定身份与说明</summary><code>${h(value.id)}</code><label>说明<textarea name="description">${h(value.description)}</textarea></label></details><p role="status"></p><footer><button type="button" data-close>取消</button><button type="submit" class="primary-button" data-tutorial="creative-save">保存并形成版本</button></footer></form>`;disposeSpecial=mountMapEditor(dialog.querySelector<HTMLElement>('[data-special-editor]')!,value,options.index,options.snapshot,persist);}
 function persist(){dirty=true;try{localStorage.setItem(storageKey,JSON.stringify({base,object:value}));}catch{}}
 const findField=(parts:string[]):ModuleField|undefined=>{let list=definition!.fields,f:ModuleField|undefined;for(let i=0;i<parts.length;i++){f=list.find(x=>x.key===parts[i]);if(!f)return;if(f.kind==='rows'){list=f.fields??[];i++;}}return f;};
 const close=()=>{if(busy)return;if(dirty&&!confirm('关闭编辑并保留本机草稿？正式文档不会改变。'))return;disposeSpecial?.();dialog.close();dialog.remove();window.removeEventListener('beforeunload',beforeUnload);};
 const beforeUnload=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',beforeUnload);
 dialog.oncancel=e=>{e.preventDefault();close();};dialog.oninput=e=>{const el=e.target as HTMLInputElement;if(el.name==='title')value.title=el.value;else if(el.name==='description')value.description=el.value;else if(el.dataset.field){const v=el instanceof HTMLSelectElement&&el.multiple?Array.from(el.selectedOptions).map(o=>o.value).filter(Boolean):el.dataset.kind==='number'?Number(el.value):el.value;set(el.dataset.field,v);}persist();};
 dialog.onclick=e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!b)return;if(b.hasAttribute('data-close'))return close();
  if(b.dataset.rowAdd){const path=b.dataset.rowAdd,f=findField(path.split('.'));const row:Data={id:'row-'+crypto.randomUUID().slice(0,8)};for(const sf of f?.fields??[]){if(sf.key==='id')continue;row[sf.key]=sf.kind==='number'?0:sf.kind==='objects'||sf.kind==='rows'?[]:'';}set(path,[...asRows(get(path)),row]);persist();render();}
  if(b.dataset.rowDelete){const [path,n]=b.dataset.rowDelete.split(':');const rows=asRows(get(path));rows.splice(Number(n),1);set(path,rows);persist();render();}
  if(b.dataset.rowMove){const [path,n,d]=b.dataset.rowMove.split(':'),rows=asRows(get(path)),a=Number(n),target=a+Number(d);if(target<0||target>=rows.length)return;[rows[a],rows[target]]=[rows[target],rows[a]];set(path,rows);persist();render();}
 };
 dialog.onsubmit=e=>{e.preventDefault();if(busy)return;const status=dialog.querySelector<HTMLElement>('[role=status]')!;const errors=validateObject(value);if(errors.length){status.textContent=errors.join('；');return;}busy=true;dialog.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=true);const docId=(dialog.querySelector('[name=document]') as HTMLSelectElement).value,doc=options.snapshot.documents.find(d=>d.id===docId);const action=doc?'save-object':'new-object';const data=doc?{object:value,documentId:doc.id,baseHash:doc.hash}:{objectId:value.id,documentId:newDocumentId,type:value.type,title:value.title,data:value.data,description:value.description};
  void creativeAction<ProjectSnapshot>(options.snapshot.project.id,action,{...data,requestId}).then(snapshot=>{dirty=false;try{localStorage.removeItem(storageKey);}catch{};window.dispatchEvent(new CustomEvent('cewen:tutorial-evidence',{detail:{name:'object-saved',projectId:snapshot.project.id,objectId:value.id,type:value.type}}));options.onSaved(snapshot);disposeSpecial?.();dialog.close();dialog.remove();window.removeEventListener('beforeunload',beforeUnload);}).catch(error=>{status.textContent=error.message+'；输入保留，可以复制后重新读取基准。';}).finally(()=>{busy=false;dialog.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=false);});
 };
 render();document.body.append(dialog);dialog.showModal();return dialog;
}
