import type { ProjectSnapshot } from '../../shared/model';
import { presets,buildPreset } from '../../shared/creative/presets';
import { prepareDirectoryFields } from '../edition';
import { creativeAction,request,connectProjects } from '../project-client';
import { h } from './render';
export async function openPresetDialog(snapshot:ProjectSnapshot|undefined,apply:(snapshot:ProjectSnapshot)=>void,append=false){
 const library=await connectProjects(),dialog=document.createElement('dialog');dialog.className='project-dialog creative-editor';const requestId=crypto.randomUUID(),instanceId='preset-'+crypto.randomUUID().slice(0,16);let busy=false;
 dialog.innerHTML=`<header class="project-dialog-header"><div><span class="eyebrow">START WITH CONTENT · NOT LIMITS</span><h1>${append?'追加预设结构':'从预设新建项目'}</h1><p>预设只提供工作起点，不写入示例回答或演示媒体；所有模块始终可用。</p></div><button type="button" data-close>×</button></header><form class="creative-preset-form"><div class="creative-preset-grid" data-tutorial="preset-picker">${presets.map(p=>`<label><input type="radio" name="preset" value="${p.id}" ${p.id==='mixed'?'checked':''}/><strong>${p.title}</strong><span>${p.description}</span></label>`).join('')}</div>${append?`<p>将追加到：${h(snapshot?.project.name)}</p>`:`<label>项目名称<input name="name" value="我的创作项目" required maxlength="100"/></label><label>项目保存父目录<input name="directory" value="${h(library.defaultDirectory)}" required/></label>`}<details open><summary>将创建的内容</summary><div data-preview></div></details><p role="status"></p><footer><button type="button" data-close>取消</button><button type="submit" class="primary-button">${append?'确认追加，不覆盖已有内容':'创建并打开'}</button></footer></form>`;
 function preview(){const data=new FormData(dialog.querySelector('form')!),preset=String(data.get('preset')),content=buildPreset(preset,instanceId,false);dialog.querySelector('[data-preview]')!.innerHTML=`<p>${content.documents.length} 份起步文档 · ${content.documents.reduce((n,d)=>n+d.objects.length,0)} 个空白创作对象</p><p>${content.documents.map(d=>h(d.title)).join(' · ')||'空白项目：从模块目录按需添加。'}</p><p class="creative-note">不会预置虚构回答、演示素材或模型验收结果。所有模块始终可用。</p>`;}
 dialog.onchange=preview;dialog.onclick=e=>{if((e.target as HTMLElement).closest('[data-close]')&&!busy){dialog.close();dialog.remove();}};dialog.oncancel=e=>{if(busy)e.preventDefault();};
 dialog.onsubmit=e=>{e.preventDefault();if(busy)return;busy=true;dialog.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=true);const data=new FormData(dialog.querySelector('form')!),status=dialog.querySelector<HTMLElement>('[role=status]')!;status.textContent='正在创建预设起点，请勿重复提交。';const input={requestId,instanceId,preset:data.get('preset'),sample:false,name:data.get('name'),demo:false,directory:data.get('directory')};const action=append&&snapshot?creativeAction<ProjectSnapshot>(snapshot.project.id,'preset-apply',input):request<ProjectSnapshot>('/api/creative-project',input);
  void action.then(next=>{dialog.close();dialog.remove();apply(next);window.dispatchEvent(new CustomEvent('cewen:creative-request',{detail:{action:'overview'}}));}).catch(error=>{status.textContent=error.message+'。已创建的部分保留，可使用同一请求重试。';}).finally(()=>{busy=false;dialog.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=false);});
 };
 document.body.append(dialog);prepareDirectoryFields(dialog);preview();dialog.showModal();
}
