import type { ProjectSnapshot } from '../../shared/model';
import { presets,buildPreset } from '../../shared/creative/presets';
import { prepareDirectoryFields,isWebEdition } from '../edition';
import { creativeAction,request,connectProjects } from '../project-client';
import { h } from './render';
export async function openPresetDialog(snapshot:ProjectSnapshot|undefined,apply:(snapshot:ProjectSnapshot)=>void,append=false,options:{practice?:boolean}={}){
 const library=await connectProjects(),dialog=document.createElement('dialog');dialog.className='project-dialog creative-editor';const requestId=crypto.randomUUID(),instanceId='preset-'+crypto.randomUUID().slice(0,16);let busy=false;
 dialog.innerHTML=`<header class="project-dialog-header"><div><span class="eyebrow">START WITH CONTENT · NOT LIMITS</span><h1>${append?'追加模板与示例':'建立创作项目'}</h1><p>预设只提供起步资料。游戏、剧本及任何项目均可使用所有模块。</p></div><button type="button" data-close>×</button></header><form class="creative-preset-form"><div class="creative-preset-grid" data-tutorial="preset-picker">${presets.map(p=>`<label><input type="radio" name="preset" value="${p.id}" ${p.id==='mixed'?'checked':''}/><strong>${p.title}</strong><span>${p.description}</span></label>`).join('')}</div><label>起点<select name="sample"><option value="yes">带完整虚构示例</option><option value="no">仅空框架</option></select></label>${append?`<p>将追加到：${h(snapshot?.project.name)}</p>`:`<label>项目名称<input name="name" value="雾港来信 · 创作练习" required maxlength="100"/></label><label class="creative-choice"><input name="demo" type="checkbox" checked ${options.practice?'disabled':''}/>在独立练习目录创建${isWebEdition?'（浏览器本机存储，可导出）':''}</label><label>正式项目保存父目录<input name="directory" value="${h(library.defaultDirectory)}"/></label>`}<details open><summary>将创建的内容</summary><div data-preview></div></details><p role="status"></p><footer><button type="button" data-close>取消</button><button type="submit" class="primary-button">${append?'确认追加，不覆盖已有内容':'创建并打开'}</button></footer></form>`;
 function preview(){const data=new FormData(dialog.querySelector('form')!),preset=String(data.get('preset')),sample=data.get('sample')==='yes',content=buildPreset(preset,instanceId,sample);dialog.querySelector('[data-preview]')!.innerHTML=`<p>${content.documents.length} 份起步文档 · ${content.documents.reduce((n,d)=>n+d.objects.length,0)} 个创作对象${sample?' · 内置示意图与合成演示配音':''}</p><p>${content.documents.map(d=>h(d.title)).join(' · ')||'空白项目：从模块目录按需添加。'}</p><p class="creative-note">${sample?'示例问题、回答与提案都明确标记为演示数据，不是你的真实回答，也不表示有模型正在连接。':''}所有模块始终可用。</p>`;const directory=dialog.querySelector<HTMLInputElement>('[name=directory]');if(directory){const demo=(dialog.querySelector('[name=demo]') as HTMLInputElement).checked;directory.required=!demo;directory.closest('label')!.hidden=demo;}}
 dialog.onchange=preview;dialog.onclick=e=>{if((e.target as HTMLElement).closest('[data-close]')&&!busy){dialog.close();dialog.remove();}};dialog.oncancel=e=>{if(busy)e.preventDefault();};
 dialog.onsubmit=e=>{e.preventDefault();if(busy)return;busy=true;dialog.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=true);const data=new FormData(dialog.querySelector('form')!),status=dialog.querySelector<HTMLElement>('[role=status]')!;status.textContent='正在创建独立内容与演示版本链，请勿重复提交。';const input={requestId,instanceId,preset:data.get('preset'),sample:data.get('sample')==='yes',name:data.get('name'),demo:options.practice===true||data.has('demo'),directory:data.get('directory')};const action=append&&snapshot?creativeAction<ProjectSnapshot>(snapshot.project.id,'preset-apply',input):request<ProjectSnapshot>('/api/creative-project',input);
  void action.then(next=>{dialog.close();dialog.remove();apply(next);window.dispatchEvent(new CustomEvent('cewen:creative-request',{detail:{action:'overview'}}));}).catch(error=>{status.textContent=error.message+'。已创建的部分保留，可使用同一请求重试。';}).finally(()=>{busy=false;dialog.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=false);});
 };
 document.body.append(dialog);prepareDirectoryFields(dialog);preview();dialog.showModal();
}
