import {detectMedia,MEDIA_LIMIT} from '../../shared/creative/media';
import type { ProjectSnapshot } from '../../shared/model';
import { buildCreativeIndex } from '../../shared/creative/content';
import { asString,asData,asRows,type CreativeObject } from '../../shared/creative/model';
import { readJobReceipt,type ProductionJob } from '../../shared/creative/production';
import { creativeAction,uploadProjectMedia,projectAction,readProject } from '../project-client';
import { isWebEdition } from '../edition';
import { h,mediaMarkup,hydrateMedia } from './render';
import { downloadText } from './player';
export async function mediaInput(file:File){
 const url=URL.createObjectURL(file);try{if(file.type.startsWith('image/')){const image=await createImageBitmap(file);image.close();return 0;}
  if(file.type.startsWith('audio/')||/\.(wav|mp3|ogg|m4a)$/i.test(file.name))return await new Promise<number>((resolve,reject)=>{const audio=new Audio(url),timer=setTimeout(()=>{audio.removeAttribute('src');reject(new Error('音频无法读取时长'));},6000);audio.onloadedmetadata=()=>{clearTimeout(timer);const value=audio.duration;audio.removeAttribute('src');Number.isFinite(value)&&value>0?resolve(Math.round(value*1000)):reject(new Error('音频时长无效'));};audio.onerror=()=>{clearTimeout(timer);reject(new Error('音频无法解码'));};});
  // 服务端还会根据内容签名判断，不信任用户提供的扩展名。
  return 0;
 }finally{URL.revokeObjectURL(url);}
}
export class ProductionPanel {
 private batch?:CreativeObject;private jobs:(ProductionJob&{stale:boolean})[]=[];private receipt?:ReturnType<typeof readJobReceipt>;private files:File[]=[];private workflow?:Record<string,unknown>;private disposeMedia?:()=>void;private busy=false;private disposed=false;private selectedRows=new Set<number>();private importGeneration=0;
 constructor(private host:HTMLElement,private snapshot:ProjectSnapshot,private batchId:string,private apply:(s:ProjectSnapshot)=>void){void this.load();}
 private status(text:string){const el=this.host.querySelector('[role=status]');if(el)el.textContent=text;}
 async load(){try{const result=await creativeAction<{batch:CreativeObject;jobs:(ProductionJob&{stale:boolean})[]}>(this.snapshot.project.id,'production-read',{batchId:this.batchId});if(this.disposed)return;this.batch=result.batch;this.jobs=result.jobs;this.render();}catch(e){this.host.textContent=(e as Error).message;}}
 private render(){if(!this.batch)return;this.disposeMedia?.();const index=buildCreativeIndex(this.snapshot);this.host.innerHTML=`<section class="creative-production" data-tutorial="production-panel"><header><h2>${h(this.batch.title)}</h2><p>${h(this.batch.data.purpose)}</p><button data-export>导出生产包与回导清单</button><button data-refresh>刷新状态</button></header><p class="creative-note">已回导 ≠ 已采用。提示词使用创建批次时的固定来源；依据变化时必须重新准备任务。</p><p role="status"></p><div class="creative-job-list">${this.jobs.map(j=>`<article><header><h3>${h(j.title)}</h3><span>${j.kind==='image'?'图片':'配音'} · ${j.stale?'依据已变化':h(j.state)}</span></header><code>${h(j.id)}</code><details><summary>固定提示词与依赖</summary><pre>${h(j.prompt)}</pre><p>${Object.keys(j.dependencies).length} 个依据对象 · 修订 ${h(j.sourceRevision)}</p><button data-copy="${h(j.id)}">复制提示词</button></details><div class="creative-candidates">${j.candidates.map(c=>`<div>${mediaMarkup(c.mediaId,j.kind==='voice'?'audio':'image',j.title)}<p>${h(c.id)} ${j.adoptedMediaId===c.mediaId?'· 已采用':''}</p><button data-adopt="${h(j.id)}:${h(c.id)}" ${j.stale||j.adoptedMediaId===c.mediaId?'disabled':''}>采用候选</button></div>`).join('')||'<p>尚无候选</p>'}</div></article>`).join('')}</div><section class="creative-import" data-tutorial="production-import"><h3>批量回导</h3><p>选择输出目录和结果清单。按 jobId / candidateId 匹配，不按文件顺序猜测。</p><label>结果清单（cewen-results-1 JSON）<input data-receipt type="file" accept=".json"/></label><label>输出文件目录<input data-files type="file" multiple webkitdirectory/></label><div data-import-preview></div><button data-manual-map>没有结果清单：手工指定匹配</button><button data-import disabled>确认登记所选候选（不采用）</button></section><section class="creative-comfy"><h3>本机 ComfyUI 图片产线</h3>${isWebEdition?'<p>独立网页版使用通用文件包；本机队列连接请使用桌面版。</p>':`<p>只提交你审核过的 API 工作流；只替换选中的文本节点，不下载模型或安装节点。</p><label>本机地址<input data-comfy-url value="http://127.0.0.1:8188"/></label><button data-comfy-check>检查连接</button><label>API 工作流 JSON<input data-workflow type="file" accept=".json"/></label><label>正向提示词文本节点<select data-text-node></select></label><label>负向文本节点（可选）<select data-negative-node><option value="">不使用</option></select></label><label><input type="checkbox" data-omit-negative/>明确忽略工作流不支持的负向提示词</label><label>本次任务<select data-comfy-job>${this.jobs.filter(j=>j.kind==='image').map(j=>`<option value="${h(j.id)}">${h(j.title)}</option>`).join('')}</select></label><div data-reference-bindings></div><label><input type="checkbox" data-omit-references/>本次明确不使用尚未映射的参考</label><label>不使用参考的原因<input data-reference-reason/></label><label class="creative-choice"><input data-consent type="checkbox"/>我已审核此工作流，同意将本任务提示词提交给上述本机服务</label><button data-comfy-submit>提交这一项</button><button data-comfy-runs>查看本项目运行记录</button><div data-runs></div>`}</section></section>`;
 this.disposeMedia=hydrateMedia(this.host,this.snapshot,index);this.renderBindings();this.host.onclick=e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!b||this.busy)return;void this.click(b).catch(e=>this.status(e.message));};this.host.onchange=e=>{void this.change(e.target as HTMLInputElement).catch(e=>this.status(e.message));};
 }
 private async click(b:HTMLButtonElement){if(b.hasAttribute('data-refresh')){this.snapshot=await readProject(this.snapshot.project.id);await this.load();return;}
  if(b.hasAttribute('data-export')){const bundle=await creativeAction<Record<string,unknown>>(this.snapshot.project.id,'production-bundle',{batchId:this.batchId});downloadText(this.batchId+'-production.json',JSON.stringify(bundle,null,2));downloadText(this.batchId+'-results-template.json',JSON.stringify(bundle.receiptTemplate,null,2));window.dispatchEvent(new CustomEvent('cewen:tutorial-evidence',{detail:{name:'production-exported',projectId:this.snapshot.project.id}}));return;}
  if(b.dataset.copy){await navigator.clipboard.writeText(this.jobs.find(j=>j.id===b.dataset.copy)!.prompt);this.status('已复制固定提示词；参考图包含在生产包中。');return;}
  if(b.dataset.adopt){const [jobId,candidateId]=b.dataset.adopt.split(':'),job=this.jobs.find(j=>j.id===jobId)!;const current=await readProject(this.snapshot.project.id),target=buildCreativeIndex(current).objects.find(o=>o.object.id===job.targetId);if(!target)throw new Error('目标已移除');this.busy=true;try{this.snapshot=await creativeAction<ProjectSnapshot>(current.project.id,'production-adopt',{requestId:crypto.randomUUID(),batchId:this.batchId,jobId,candidateId,baseHash:target.hash});this.apply(this.snapshot);window.dispatchEvent(new CustomEvent('cewen:tutorial-evidence',{detail:{name:'candidate-adopted',projectId:this.snapshot.project.id}}));await this.load();}finally{this.busy=false;}return;}
  if(b.hasAttribute('data-import'))return this.import();if(b.hasAttribute('data-manual-map')){this.manualMapping();return;}
  const url=this.host.querySelector<HTMLInputElement>('[data-comfy-url]')?.value;
  if(b.hasAttribute('data-comfy-check')){const result=await projectAction<{notice:string}>(this.snapshot.project.id,'comfy',{operation:'check',url});this.status(result.notice);return;}
  if(b.hasAttribute('data-comfy-submit')){if(!this.workflow)throw new Error('请先选择 API 工作流');const confirmed=this.host.querySelector<HTMLInputElement>('[data-consent]')!.checked;if(!confirmed)throw new Error('请明确确认本次提交');const jobId=this.host.querySelector<HTMLSelectElement>('[data-comfy-job]')!.value,textNode=this.host.querySelector<HTMLSelectElement>('[data-text-node]')!.value;this.busy=true;try{const run=await projectAction<{promptId:string}>(this.snapshot.project.id,'comfy',{operation:'submit',url,batchId:this.batchId,jobId,textNode,workflow:this.workflow,confirmed,negativeNode:this.host.querySelector<HTMLSelectElement>('[data-negative-node]')!.value,omitNegative:this.host.querySelector<HTMLInputElement>('[data-omit-negative]')!.checked,referenceBindings:Array.from(this.host.querySelectorAll<HTMLSelectElement>('[data-reference-node]')).filter(s=>s.value).map(s=>({mediaId:s.dataset.referenceNode,nodeId:s.value})),omitReferences:this.host.querySelector<HTMLInputElement>('[data-omit-references]')!.checked,referenceOmissionReason:this.host.querySelector<HTMLInputElement>('[data-reference-reason]')!.value});this.status('已提交队列：'+run.promptId+'。未自动采用。');}finally{this.busy=false;}return;}
  if(b.hasAttribute('data-comfy-runs')){const result=await projectAction<{runs:{id:string;jobId:string;state:string;message?:string}[]}>(this.snapshot.project.id,'comfy',{operation:'status',refresh:true});this.host.querySelector('[data-runs]')!.innerHTML=result.runs.map(r=>`<p>${h(r.jobId)} · ${h(r.state)} ${h(r.message)} <button data-collect="${h(r.id)}">读取结果</button><button data-cancel-run="${h(r.id)}">取消待执行项</button></p>`).join('')||'<p>本项目没有已登记运行。</p>';return;}
  if(b.dataset.collect||b.dataset.cancelRun){const result=await projectAction<{snapshot?:ProjectSnapshot;notice?:string;message?:string;state?:string}>(this.snapshot.project.id,'comfy',{operation:b.dataset.collect?'collect':'cancel',runId:b.dataset.collect??b.dataset.cancelRun});if(result.snapshot){this.snapshot=result.snapshot;this.apply(result.snapshot);await this.load();}this.status(result.message??result.notice??result.state??'操作完成');}
 }
 private renderBindings(){const host=this.host.querySelector('[data-reference-bindings]');if(!host)return;const selected=this.host.querySelector<HTMLSelectElement>('[data-comfy-job]')?.value,job=this.jobs.find(j=>j.id===selected),index=buildCreativeIndex(this.snapshot);const nodes=Object.entries(this.workflow??{}).filter(([,v])=>typeof asData(asData(v).inputs).image==='string');host.innerHTML=job?.referenceMediaIds.map(mediaId=>`<label>参考：${h(index.objects.find(o=>o.object.id===mediaId)?.object.title??mediaId)}<select data-reference-node="${h(mediaId)}"><option value="">尚未绑定 image 输入</option>${nodes.map(([id,v])=>`<option value="${h(id)}">${h(id)} · ${h(asData(v).class_type)}</option>`).join('')}</select></label>`).join('')||'<p>本任务没有外部参考媒体。</p>';}
 private async change(input:HTMLInputElement){if(input.hasAttribute('data-workflow')&&input.files?.[0]){if(input.files[0].size>2*1024*1024)throw new Error('工作流过大');this.workflow=JSON.parse(await input.files[0].text());this.host.querySelector('[data-text-node]')!.innerHTML=Object.entries(this.workflow!).filter(([,v])=>typeof asData(asData(v).inputs).text==='string').map(([id,v])=>`<option value="${h(id)}">${h(id)} · ${h(asData(v).class_type)}</option>`).join('');this.host.querySelector('[data-negative-node]')!.innerHTML='<option value="">不使用</option>'+this.host.querySelector('[data-text-node]')!.innerHTML;this.renderBindings();}
  if(input.hasAttribute('data-comfy-job')){this.renderBindings();return;}
  if(input.hasAttribute('data-receipt')&&input.files?.[0]){if(input.files[0].size>2*1024*1024)throw new Error('结果清单过大');this.receipt=readJobReceipt(JSON.parse(await input.files[0].text()));}
  if(input.hasAttribute('data-select-result')){const i=Number(input.dataset.selectResult);input.checked?this.selectedRows.add(i):this.selectedRows.delete(i);(this.host.querySelector('[data-import]') as HTMLButtonElement).disabled=!this.selectedRows.size;return;}
  if(input.hasAttribute('data-files')){this.files=Array.from(input.files??[]);if(this.files.length>1000)throw new Error('一次最多1000个文件，请分批回导');}await this.previewImport();
 }
 private fileMap(){const map=new Map<string,File>();for(const file of this.files){const path=file.webkitRelativePath?file.webkitRelativePath.split('/').slice(1).join('/'):file.name;if(map.has(path))throw new Error('输出目录中有重复路径');map.set(path,file);}return map;}
 private async previewImport(){if(!this.receipt)return;const generation=++this.importGeneration,files=this.fileMap(),rows=this.receipt.results;this.selectedRows.clear();const seen=new Set<string>(),previews:{text:string;valid:boolean;label:string}[]=[];
  for(const [i,r] of rows.entries()){const file=files.get(r.filename),job=this.jobs.find(j=>j.id===r.jobId),duplicate=seen.has(r.jobId+':'+r.candidateId);seen.add(r.jobId+':'+r.candidateId);let reason='',valid=true;
   if(this.receipt.batchId!==this.batchId){reason='错误批次';valid=false;}else if(!job){reason='未知任务，须人工映射';valid=false;}else if(!file){reason='缺少文件';valid=false;}else if(duplicate){reason='同任务候选身份重复';valid=false;}else if(job.candidates.some(c=>c.id===r.candidateId)){reason='候选身份已登记；不会覆盖';valid=false;}else if(file.size>MEDIA_LIMIT){reason='超过64 MiB';valid=false;}else{try{const bytes=new Uint8Array(await file.slice(0,64).arrayBuffer()),type=detectMedia(bytes);if(type.kind!==(job.kind==='voice'?'audio':'image'))throw new Error('媒体类型不匹配');reason=job.stale?'来源已变化；只登记过期候选':'身份与内容签名匹配；登记前会实际解码';}catch(e){reason=(e as Error).message;valid=false;}}
   previews.push({text:r.filename+' → '+(job?.title??r.jobId),valid,label:reason});if(valid)this.selectedRows.add(i);
  }
  if(this.disposed||generation!==this.importGeneration)return;
  this.host.querySelector('[data-import-preview]')!.innerHTML=previews.map((row,i)=>`<label class="creative-choice"><input type="checkbox" data-select-result="${i}" ${row.valid?'checked':'disabled'}/><span>${h(row.text)}<small>${h(row.label)}</small></span></label>`).join('')+`<p>${this.files.filter(f=>!rows.some(r=>files.get(r.filename)===f)).length} 个文件没有匹配，不会自动导入。只处理勾选项。</p>`;
  (this.host.querySelector('[data-import]') as HTMLButtonElement).disabled=!this.selectedRows.size;
 }
 /** 无回执时让人明确逐文件选择目标，绝不把排序当成镜头身份。 */
 private manualMapping(){if(!this.files.length){this.status('请先选择输出文件目录。');return;}const files=this.fileMap(),dialog=document.createElement('dialog');dialog.className='project-dialog creative-editor';dialog.innerHTML=`<header class="project-dialog-header"><h2>人工确认回导映射</h2><button data-close>×</button></header><p>未选目标的文件不会导入。确认后仍进行类型和身份检查。</p><form>${[...files].map(([path],i)=>`<label>${h(path)}<select name="map-${i}"><option value="">不导入</option>${this.jobs.map(j=>`<option value="${h(j.id)}">${h(j.title)} · ${j.kind==='voice'?'配音':'图片'}</option>`).join('')}</select></label>`).join('')}<button class="primary-button">确认映射并预检</button></form>`;dialog.querySelector('[data-close]')!.addEventListener('click',()=>{dialog.close();dialog.remove();});dialog.onsubmit=e=>{e.preventDefault();const data=new FormData(dialog.querySelector('form')!),results=[...files].flatMap(([filename],i)=>{const jobId=String(data.get('map-'+i));return jobId?[{jobId,filename,candidateId:'candidate-'+crypto.randomUUID()}]:[];});this.receipt={format:'cewen-results-1',batchId:this.batchId,results};dialog.close();dialog.remove();void this.previewImport().catch(e=>this.status(e.message));};document.body.append(dialog);dialog.showModal();}
 private async import(){if(!this.receipt||this.receipt.batchId!==this.batchId)throw new Error('结果清单与批次不匹配');const files=this.fileMap();this.busy=true;let count=0;const errors:string[]=[];
  try{for(const [row,result] of this.receipt.results.entries()){if(!this.selectedRows.has(row))continue;try{const file=files.get(result.filename);if(!file||!this.jobs.some(j=>j.id===result.jobId))throw new Error('文件或任务不存在');if(file.size>MEDIA_LIMIT)throw new Error('媒体超过64 MiB');const type=detectMedia(new Uint8Array(await file.slice(0,64).arrayBuffer())),job=this.jobs.find(j=>j.id===result.jobId)!;if(type.kind!==(job.kind==='voice'?'audio':'image'))throw new Error('媒体类型不匹配');const durationMs=await mediaInput(new File([file],file.name,{type:type.mime})),media=await uploadProjectMedia(this.snapshot.project.id,file,{requestId:crypto.randomUUID(),durationMs,permission:'用户批量回导；采用前需核对来源使用许可'});this.snapshot=await creativeAction<ProjectSnapshot>(this.snapshot.project.id,'production-result',{requestId:crypto.randomUUID(),batchId:this.batchId,jobId:result.jobId,candidateId:result.candidateId,mediaId:media.mediaId});count++;}catch(e){errors.push(result.filename+'：'+(e as Error).message);}}
   this.apply(this.snapshot);if(count)window.dispatchEvent(new CustomEvent('cewen:tutorial-evidence',{detail:{name:'candidates-imported',projectId:this.snapshot.project.id,count}}));await this.load();this.status(`已登记 ${count} 个候选，没有自动采用。${errors.length?'未完成：'+errors.join('；'):''}`);
  }finally{this.busy=false;}
 }
 dispose(){this.disposed=true;this.disposeMedia?.();this.host.onclick=null;this.host.onchange=null;}
}
