import {parseAnchor,resolveAnchor,anchorFromText} from '../../shared/creative/anchors';
import type { ProjectSnapshot,ProjectDocument } from '../../shared/model';
import { inquiry,questionAvailable } from '../../shared/inquiry';
import { readHeader } from '../../shared/markdown';
import { buildCreativeIndex } from '../../shared/creative/content';
import { asString,asStrings } from '../../shared/creative/model';
import { creativeAction,projectAction } from '../project-client';
import { h,stateLabel } from './render';
export function relatedQuestions(snapshot:ProjectSnapshot,documentId?:string,questId?:string){
 const index=buildCreativeIndex(snapshot),ids=new Set(index.objects.filter(o=>o.documentId===documentId).map(o=>o.object.id));for(const r of index.references)if(ids.has(r.ownerId))ids.add(r.targetId);
 return snapshot.documents.filter(d=>{if(d.type!=='question')return false;const m=readHeader(d.text).metadata;return questId?m.questId===questId:!documentId||asStrings(m.targets).includes(documentId)||asStrings(m.objectTargets).some(id=>ids.has(id))||((m.anchor as {documentId?:string})?.documentId===documentId);});
}
/** 问题层与 Quest 共用此表单；原话在服务中追加，而不是覆盖。 */
export function mountQuestions(host:HTMLElement,snapshot:ProjectSnapshot,questions:ProjectDocument[],apply:(snapshot:ProjectSnapshot)=>void){
 let filter='all',questFilter='all',roundFilter='all',busy=false,lastPayload='',requestId=crypto.randomUUID();const cacheKey=`cewen-answers-090:${snapshot.project.id}`;let drafts:Record<string,{hash:string;text:string;choices:string[];action:string}>={};try{const value=JSON.parse(localStorage.getItem(cacheKey)??'{}');if(value&&typeof value==='object'&&!Array.isArray(value))for(const [key,v] of Object.entries(value)){const d=v as {hash?:unknown;text?:unknown;choices?:unknown;action?:unknown};if(d&&typeof d.hash==='string'&&typeof d.text==='string'&&typeof d.action==='string'&&Array.isArray(d.choices)&&d.choices.every(v=>typeof v==='string'))drafts[key]=d as typeof drafts[string];}}catch{}
 function render(){const meta=new Map(questions.map(d=>[d.id,readHeader(d.text).metadata]));const index=buildCreativeIndex(snapshot);const quests=[...new Set(questions.map(d=>asString(meta.get(d.id)?.questId,'standalone')))];const rounds=[...new Set(questions.map(d=>inquiry(d).round))];host.innerHTML=`<div class="creative-question-controls" data-tutorial="question-filter"><label>问题筛选<select data-filter="status"><option value="all">全部</option><option value="open">待回答</option><option value="answered">已回答 · 待决定</option><option value="partially-decided">部分落实</option><option value="decided">已落实</option></select></label><label>Quest<select data-filter="quest"><option value="all">全部任务</option>${quests.map(id=>`<option value="${h(id)}">${h(id==='standalone'?'独立问题':index.objects.find(o=>o.object.id===id)?.object.title??id)}</option>`).join('')}</select></label><label>轮次<select data-filter="round"><option value="all">全部轮次</option>${rounds.map(round=>`<option value="${h(round)}">${h(round)}</option>`).join('')}</select></label><span>${questions.length} 个相关问题</span></div><form data-question-form>${questions.filter(doc=>(filter==='all'||inquiry(doc).status===filter)&&(questFilter==='all'||asString(meta.get(doc.id)?.questId,'standalone')===questFilter)&&(roundFilter==='all'||inquiry(doc).round===roundFilter)).map(doc=>{
  const q=inquiry(doc),available=questionAvailable(doc,snapshot.documents),saved=drafts[doc.id],stale=saved&&saved.hash!==doc.hash;
  const anchor=meta.get(doc.id)?.anchor,resolved=anchor?resolveAnchor(snapshot,anchor):undefined;
  return `<article class="creative-question" data-question="${h(doc.id)}"><header><small>${h(q.round)} · ${h(stateLabel(q.status))}</small><h3>${h(q.title)}</h3></header><p>${h(q.background)}</p><div class="question-source">${resolved?`<small>${h(resolved.reason)}</small><button type="button" data-source="${h(doc.id)}" ${['missing','ambiguous'].includes(resolved.state)?'disabled':''}>查看来源</button>`:''}${!snapshot.historical?`<button type="button" data-link-question="${h(doc.id)}">关联任务 / 重定位</button>`:''}</div>${!available.active?`<p class="creative-note">${h(available.reason)}</p>`:''}${stale?'<p class="creative-warning">题目或已有回答已经变化，旧草稿保留，请核对后重新填写。</p>':''}<fieldset ${snapshot.historical||!available.active?'disabled':''}>${q.options.map((opt,i)=>`<label class="creative-choice"><input type="${q.multiple?'checkbox':'radio'}" name="choice-${h(q.id)}" value="${h(opt)}" ${!stale&&saved?.choices.includes(opt)?'checked':''}/> ${h(opt)}</label>`).join('')}<label>我的补充<textarea name="answer-${h(q.id)}" rows="2">${h(!stale?saved?.text:'')}</textarea></label><label>作答方式<select name="action-${h(q.id)}"><option value="">本次不回答</option><option value="回答" ${!stale&&saved?.action==='回答'?'selected':''}>提交回答</option><option value="暂缓" ${!stale&&saved?.action==='暂缓'?'selected':''}>暂缓</option><option value="前提不成立" ${!stale&&saved?.action==='前提不成立'?'selected':''}>前提不成立</option></select></label></fieldset><details><summary>原始回答与决定</summary><pre>${h(q.previous)}</pre><p>${h(q.interpretation)}</p><p>${h(q.decision)}</p></details></article>`;
 }).join('')||'<p class="creative-empty">当前范围没有问题，可对文档或模块发起 Quest。</p>'}<p role="status"></p>${!snapshot.historical&&questions.length?'<button type="submit" class="primary-button" data-tutorial="quest-answer">提交本轮已填写回答</button>':''}</form>`;
 (host.querySelector('[data-filter=status]') as HTMLSelectElement).value=filter;(host.querySelector('[data-filter=quest]') as HTMLSelectElement).value=questFilter;(host.querySelector('[data-filter=round]') as HTMLSelectElement).value=roundFilter;
 }
 function capture(){const form=host.querySelector<HTMLFormElement>('form');if(!form)return;const data=new FormData(form);for(const doc of questions){if(!form.querySelector(`[name="answer-${CSS.escape(doc.id)}"]`))continue;const text=String(data.get('answer-'+doc.id)??''),choices=data.getAll('choice-'+doc.id).map(String),action=String(data.get('action-'+doc.id)??'');if(text||choices.length||action)drafts[doc.id]={hash:doc.hash,text,choices,action};else delete drafts[doc.id];}try{localStorage.setItem(cacheKey,JSON.stringify(drafts));}catch{}}
 host.oninput=()=>capture();host.onchange=e=>{const input=e.target as HTMLSelectElement;if(input.hasAttribute('data-filter')){capture();if(input.dataset.filter==='status')filter=input.value;else if(input.dataset.filter==='quest')questFilter=input.value;else roundFilter=input.value;render();window.dispatchEvent(new CustomEvent('cewen:tutorial-evidence',{detail:{name:'questions-filtered',projectId:snapshot.project.id}}));}};
 host.onsubmit=e=>{e.preventDefault();if(busy)return;capture();const answers=questions.filter(q=>drafts[q.id]?.hash===q.hash).map(q=>({documentId:q.id,baseHash:q.hash,choices:drafts[q.id].choices,text:drafts[q.id].text,action:drafts[q.id].action||((drafts[q.id].text||drafts[q.id].choices.length)?'回答':'')})).filter(a=>a.action);if(!answers.length)return;const signature=JSON.stringify(answers);if(signature!==lastPayload){requestId=crypto.randomUUID();lastPayload=signature;}busy=true;const button=host.querySelector<HTMLButtonElement>('[type=submit]')!;button.disabled=true;host.querySelectorAll<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>('input,textarea,select').forEach(el=>el.disabled=true);
  void projectAction<ProjectSnapshot>(snapshot.project.id,'answers',{requestId,answers}).then(next=>{for(const a of answers)delete drafts[a.documentId];try{localStorage.setItem(cacheKey,JSON.stringify(drafts));}catch{};window.dispatchEvent(new CustomEvent('cewen:tutorial-evidence',{detail:{name:'questions-answered',projectId:snapshot.project.id}}));apply(next);}).catch(error=>{host.querySelector<HTMLElement>('[role=status]')!.textContent=error.message;}).finally(()=>{busy=false;if(button.isConnected){button.disabled=false;host.querySelectorAll<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>('input,textarea,select').forEach(el=>{if(!el.closest('fieldset[disabled]'))el.disabled=false;});}});
 };
 host.onclick=event=>{const button=(event.target as HTMLElement).closest<HTMLButtonElement>('button');if(!button)return;const qid=button.dataset.source??button.dataset.linkQuestion;if(!qid)return;const doc=questions.find(q=>q.id===qid)!;const anchor=readHeader(doc.text).metadata.anchor;
  if(button.dataset.source){const resolved=resolveAnchor(snapshot,anchor);if(resolved.state==='missing'||resolved.state==='ambiguous')return;window.dispatchEvent(new CustomEvent('cewen:locate-anchor',{detail:{anchor,resolved}}));return;}
  capture();const index=buildCreativeIndex(snapshot),saved=parseAnchor(anchor),dialog=document.createElement('dialog');dialog.className='project-dialog creative-editor';dialog.innerHTML=`<header class="project-dialog-header"><h2>关联问题与来源</h2><button type="button" data-close>×</button></header><p>只修改明确关联；问题原文、用户回答和既有决定保持不变。</p><form><label>归属 Quest<select name="quest"><option value="">独立问题</option>${index.objects.filter(o=>o.object.type==='quest').map(o=>`<option value="${h(o.object.id)}" ${o.object.id===readHeader(doc.text).metadata.questId?'selected':''}>${h(o.object.title)}</option>`).join('')}</select></label><label>来源文档<select name="document"><option value="">保留当前来源</option>${snapshot.documents.filter(d=>d.type!=='question').map(d=>`<option value="${h(d.id)}" ${d.id===saved.documentId?'selected':''}>${h(d.title)}</option>`).join('')}</select></label><label>绑定稳定对象（优先于文字）<select name="object"><option value="">文档或文字段落</option>${index.objects.map(o=>`<option value="${h(o.object.id)}" ${o.object.id===saved.objectId?'selected':''}>${h(o.object.title)}</option>`).join('')}</select></label><label>明确摘录<textarea name="excerpt">${h(saved.excerpt??'')}</textarea></label><p role="status"></p><button type="submit" class="primary-button">校验并更新关联</button></form>`;
  dialog.querySelector('[data-close]')!.addEventListener('click',()=>{dialog.close();dialog.remove();});dialog.onsubmit=e=>{e.preventDefault();if(busy)return;const data=new FormData(dialog.querySelector('form')!),objectId=String(data.get('object')??''),documentId=objectId?index.objects.find(o=>o.object.id===objectId)?.documentId:String(data.get('document')??'');const nextAnchor=documentId?{...anchorFromText(snapshot,documentId,String(data.get('excerpt')??'')),...(objectId?{objectId}:{})}:undefined;busy=true;void creativeAction<ProjectSnapshot>(snapshot.project.id,'question-link',{requestId:crypto.randomUUID(),questionId:qid,baseHash:doc.hash,questId:String(data.get('quest')??''),...(nextAnchor?{anchor:nextAnchor}:{})}).then(next=>{dialog.close();dialog.remove();apply(next);}).catch(err=>dialog.querySelector('[role=status]')!.textContent=err.message).finally(()=>busy=false);};document.body.append(dialog);dialog.showModal();
 };render();return()=>{host.oninput=null;host.onchange=null;host.onsubmit=null;host.onclick=null;};
}
