import { asString,asNumber,asRows,asStrings,type CreativeIndex,type CreativeObject,type Data } from '../../shared/creative/model';
import { moduleRegistry } from '../../shared/creative/registry';
import { acquireMediaUrl,loadMediaUrl } from '../project-client';
import type { ProjectSnapshot } from '../../shared/model';
export const h=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const num=(v:unknown)=>Math.max(0,Math.min(1,asNumber(v)));
const coords=(value:unknown)=>asString(value).split(';').slice(0,1000).map(p=>p.trim().split(',').map(Number)).filter(p=>p.length===2&&p.every(Number.isFinite)).map(([x,y])=>`${num(x)*960},${num(y)*540}`).join(' ');
export function mediaMarkup(id:string,kind:'image'|'audio'='image',alt='分镜参考'){return id?(kind==='image'?`<img class="creative-image" data-creative-media="${h(id)}" alt="${h(alt)}" loading="lazy"/>`:`<audio data-creative-media="${h(id)}" controls preload="none" aria-label="${h(alt)}"></audio>`):`<div class="creative-placeholder">${kind==='image'?'暂无图片 · 可先进行文字排演':'暂无配音 · 不自动生成'}</div>`;}
function objectLink(id:string,index:CreativeIndex){const o=index.objects.find(x=>x.object.id===id)?.object;return `<button type="button" class="creative-link" data-object-open="${h(id)}">${h(o?.title??'缺失：'+id)}</button>`;}
function mapView(o:CreativeObject,index:CreativeIndex){const base=o.type==='map-use'?index.objects.find(x=>x.object.id===o.data.mapId)?.object:o,baseData=base?.data??{},layers=o.type==='map-use'?[baseData,o.data]:[o.data];
 return `<div class="creative-map">${mediaMarkup(asString(baseData.mediaId),'image',base?.title??'地图')}<svg viewBox="0 0 960 540" role="img" aria-label="${h(o.title)}二维覆盖层">${layers.map((d,layer)=>`<g class="map-layer-${layer}">${asRows(d.areas).map(a=>`<polygon points="${coords(a.points)}"><title>${h(a.label)}</title></polygon>`).join('')}${asRows(d.paths).map(p=>`<polyline points="${coords(p.points)}"><title>${h(p.label)}</title></polyline>`).join('')}${asRows(d.points).map(p=>`<g><circle cx="${num(p.x)*960}" cy="${num(p.y)*540}" r="8"/><text x="${num(p.x)*960+12}" y="${num(p.y)*540-12}">${h(p.label)}</text></g>`).join('')}</g>`).join('')}</svg></div><p class="creative-note">${h(baseData.units??'仅二维示意，不是实际摄影机坐标')} ${o.type==='map-use'?`· 本层：${h(o.data.purpose)} · 共享底图 ${objectLink(asString(o.data.mapId),index)}`:''}</p>`;
}
/** 所有卡片只投影共享 Markdown 对象；引用展开有深度界限，不递归复制数据。 */
export function objectCard(o:CreativeObject,index:CreativeIndex,compact=false,depth=0):string {
 const d=o.data,lookup=(id:string)=>index.objects.find(x=>x.object.id===id)?.object;let body='';
 switch(o.type){
  case 'map':case 'map-use':body=mapView(o,index);break;
  case 'character':body=`${mediaMarkup(asString(d.mediaId),'image',o.title)}<p>${h(d.identity)}</p><p>${h(d.motivation)}</p><p>${h(d.personality)}</p>${d.voiceId?objectLink(asString(d.voiceId),index):''}<div class="creative-chips">${asRows(d.variants).map(v=>`<span title="${h(v.description)}">${h(v.name)}</span>`).join('')}</div>`;break;
  case 'location':body=`<p>${h(d.space)}</p><p>${h(d.time)} · ${h(d.lighting)}</p>${d.mapId?objectLink(asString(d.mapId),index):''}${d.mediaId?mediaMarkup(asString(d.mediaId)):''}`;break;
  case 'voice':body=`<p>${h(d.language)} · ${h(d.style)}</p><p class="creative-note">${h(d.permission)}</p>${mediaMarkup(asString(d.sampleMediaId),'audio','试音')}`;break;
  case 'speech':body=`<p class="creative-kicker">${h(d.mode)} · ${d.characterId?objectLink(asString(d.characterId),index):'未指定角色'}</p><blockquote>${h(d.text)}</blockquote><p>${h(d.performance)}</p>${mediaMarkup(asString(d.mediaId),'audio','采用配音')}`;break;
  case 'scene':body=`<p>${h(d.interior)} · ${h(d.time)} · ${d.locationId?objectLink(asString(d.locationId),index):'未指定地点'}</p><p><strong>场次目标</strong> ${h(d.goal)}</p><p>${h(d.action)}</p><div class="creative-chips">${asStrings(d.characterIds).map(id=>objectLink(id,index)).join('')}</div><details><summary>对白与旁白 ${asStrings(d.speechIds).length} 条</summary>${asStrings(d.speechIds).map(id=>`<p>${objectLink(id,index)} ${h(lookup(id)?.data.text)}</p>`).join('')}</details>`;break;
  case 'shot':body=`<p>${h(d.framing)} · ${h(d.movement)} · ${(asNumber(d.estimatedMs)/1000).toFixed(1)} 秒</p><p>${h(d.action)}</p><div class="creative-boards">${asRows(d.panels).map(p=>`<figure>${mediaMarkup(asString(p.mediaId),'image',asString(p.caption))}<figcaption>${h(p.caption)} <small>${h(p.id)}</small></figcaption></figure>`).join('')||'<p>尚无分镜画面，可先新增一张文字画面。</p>'}</div><div class="creative-chips">${[asString(d.sceneId),asString(d.mapUseId),...asStrings(d.speechIds)].filter(Boolean).map(id=>objectLink(id,index)).join('')}</div>`;break;
  case 'storyline':body=`<p>排演路径：${h(d.selectedPath||'尚未选择')}</p>${d.mapUseId?objectLink(asString(d.mapUseId),index):''}<ol class="creative-beats">${asRows(d.nodes).map(n=>`<li><strong>${h(n.title)}</strong><small>${h(n.id)} → ${h(n.next||'结束')}</small><p>${h(n.text)}</p>${n.sceneId?objectLink(asString(n.sceneId),index):''}</li>`).join('')}</ol>`;break;
  case 'sequence':body=`<p>${h(d.path)}</p><p>${asRows(d.items).length} 个镜头实例 · ${asRows(d.audio).length} 条声音位置</p><button type="button" class="primary-button" data-sequence-play="${h(o.id)}">播放二维排演</button><div class="creative-chips">${asRows(d.items).slice(0,20).map(r=>objectLink(asString(r.shotId),index)).join('')}</div>`;break;
  case 'quest':body=`<p>${h(d.goal)}</p><p>${h(d.scope)}</p><p>${h(({confirmed:'决定已确认',"not-confirmed":'待确认决定',"needs-review":'确认依据已变化',open:'进行中',paused:'已暂停',closed:'已关闭',archived:'已归档'} as Record<string,string>)[asString(d.state)]??d.state)} · ${asRows(d.rounds).length} 轮</p><button type="button" class="primary-button" data-quest-open="${h(o.id)}">进入 Quest</button>`;break;
  case 'reference':{const ref=lookup(asString(d.objectId));body=`<p>引用源：${objectLink(asString(d.objectId),index)}</p><p>${h(d.note)}</p>${!compact&&ref&&depth<1?objectCard(ref,index,true,depth+1):''}`;break;}
  case 'decision':body=`<p>${h(d.text)}</p><p>${h(d.rationale)}</p><p class="creative-note">记录不等于自动采纳；以问题原话与提案落实情况为准。</p>`;break;
  case 'media':body=`${mediaMarkup(o.id,asString(d.mime).startsWith('audio/')?'audio':'image',o.title)}<p>${h(d.mime)} · ${(asNumber(d.bytes)/1024).toFixed(1)} KiB</p><p class="creative-note">${h(d.permission)}</p>`;break;
  case 'production':body=`<p>${h(d.purpose)}</p><p>${asRows(d.jobs).length} 个固定身份的生成任务</p><button type="button" class="secondary-button" data-production-open="${h(o.id)}">查看任务与候选</button>`;break;
  case 'dialogue':body=`<p>互动对白 · ${asRows(d.nodes).length} 个节点</p>${asRows(d.nodes).slice(0,compact?2:8).map(n=>`<p><b>${h(n.speaker)}</b> ${h(n.text)}</p>`).join('')}`;break;
  case 'palette':body=`<div class="creative-chips">${asRows(d.colors).map(c=>`<span><i style="background:${/^#[\dA-Fa-f]{6}$/.test(asString(c.hex))?asString(c.hex):'#888'};display:inline-block;width:20px;height:20px"></i> ${h(c.hex)} ${h(c.role)}</span>`).join('')}</div>`;break;
  default:body='<p>未知模块保留原文。请使用支持它的版本，不做破坏性回写。</p>';
 }
 const uses=index.references.filter(r=>r.targetId===o.id).length;
 return `<article class="creative-object ${compact?'compact':''}" data-creative-object="${h(o.id)}" data-tutorial="creative-object"><header><span>${h(moduleRegistry.get(o.type)?.title??o.type)}</span><h3>${h(o.title)}</h3><small>${uses} 处引用</small></header><div class="creative-object-body">${body}</div>${!compact?`<footer>${o.type==='decision'?`<button data-confirm-decision="${h(o.id)}">明确确认决定</button>`:''}<button type="button" data-object-edit="${h(o.id)}">编辑源对象</button><button type="button" data-object-reference="${h(o.id)}">引用到文档</button><button type="button" data-object-copy="${h(o.id)}">独立复制</button><button type="button" data-quest-target="${h(o.id)}">对此发起 Quest</button></footer>`:''}</article>`;
}
/** 媒体只在实际可见或点击播放时请求；失败不伪装为已经看见图片。 */
export function hydrateMedia(root:ParentNode,snapshot:ProjectSnapshot,index:CreativeIndex){
 let disposed=false;const releases=new Map<HTMLElement,()=>void>();
 const media=new Map(index.objects.filter(x=>x.object.type==='media').map(x=>[x.object.id,x.object]));
 const load=async(el:HTMLElement)=>{if(el.dataset.loading)return;el.dataset.loading='true';const o=media.get(el.dataset.creativeMedia??'');if(!o){el.replaceWith(Object.assign(document.createElement('p'),{className:'creative-note',textContent:'素材尚未登记或不在此版本中'}));return;}
  try{const lease=await acquireMediaUrl(snapshot,asString(o.data.path));if(disposed||!el.isConnected){lease.release();return;}releases.set(el,lease.release);const url=lease.url;if(el instanceof HTMLImageElement||el instanceof HTMLAudioElement){el.onerror=()=>{el.replaceWith(Object.assign(document.createElement('p'),{className:'creative-warning',textContent:'媒体无法解码，请重新导入有效文件'}));};el.src=url;if(el instanceof HTMLAudioElement)el.addEventListener('play',()=>window.dispatchEvent(new CustomEvent('cewen:tutorial-evidence',{detail:{name:'voice-played',projectId:snapshot.project.id}})),{once:true});}}
  catch(e){if(el.isConnected)el.replaceWith(Object.assign(document.createElement('p'),{className:'creative-note',textContent:'媒体不可用：'+String((e as Error).message)}));}
 };
 const elements=Array.from(root.querySelectorAll<HTMLElement>('[data-creative-media]'));
 if(!('IntersectionObserver' in window)){elements.forEach(el=>void load(el));return()=>{disposed=true;for(const release of releases.values())release();releases.clear();};}
 const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){observer.unobserve(entry.target);void load(entry.target as HTMLElement);}},{rootMargin:'200px'});elements.forEach(el=>observer.observe(el));return()=>{disposed=true;observer.disconnect();for(const [el,release] of releases){if(el instanceof HTMLAudioElement){el.pause();el.removeAttribute('src');el.load();}release();}releases.clear();};
}

export function stateLabel(value:unknown){const key=asString(value);return ({confirmed:'决定已确认',"not-confirmed":'待确认决定',"needs-review":'确认依据已变化',open:'进行中',paused:'已暂停',closed:'已关闭',archived:'已归档',answered:'已回答',"waiting-user":'待用户回答',"not-applied":'尚未落实',"partially-applied":'部分落实',applied:'已落实',accepted:'已采纳',"partially-accepted":'部分采纳',proposed:'待审核',rejected:'已退回',decided:'已落实',"partially-decided":'部分落实',prepared:'已准备',returned:'已回导',adopted:'已采用'} as Record<string,string>)[key]??key;}
