import {cloneCreativeObject} from '../../shared/creative/clone';
import {anchorFromText} from '../../shared/creative/anchors';
import {queryObjects,creativeStatistics} from '../../shared/creative/query';
import type { ProjectSnapshot } from '../../shared/model';
import { buildCreativeIndex } from '../../shared/creative/content';
import { asData,asString,asRows,asStrings,type CreativeObject,type Data,type CreativeIndex } from '../../shared/creative/model';
import { moduleRegistry } from '../../shared/creative/registry';
import { presets } from '../../shared/creative/presets';
import { creativeAction,uploadProjectMedia,readProject,projectAction,request } from '../project-client';
import { prepareDirectoryFields } from '../edition';
import { h,objectCard,hydrateMedia,stateLabel } from './render';
import { openObjectEditor } from './editor';
import { mountQuestions,relatedQuestions } from './questions';
import { AnimaticPlayer,downloadText } from './player';
import { ProductionPanel,mediaInput } from './production-panel';
import { openPresetDialog } from './preset-dialog';
import { readHeader } from '../../shared/markdown';
export type CreativeTab='objects'|'quests'|'sequences'|'production'|'presets';
/** 创作模式不依赖项目预设；选择什么预设都能调用全部模块。 */
export class CreativeWorkspace {
 private snapshot?:ProjectSnapshot;private tab:CreativeTab='objects';private selected='';private filter='';private query='';private statusFilter='';private tagFilter='';private relatedFilter='';private questFilter='';private missingOnly=false;private page=0;private disposeContent?:()=>void;private generation=0;
 constructor(private host:HTMLElement,private applyProject:(s:ProjectSnapshot)=>void,private review:()=>void){
  document.addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-object-open],[data-object-edit],[data-object-reference],[data-object-copy],[data-quest-target],[data-quest-open],[data-sequence-play],[data-production-open],[data-document-module],[data-document-quest],[data-confirm-decision]');if(!b||b.closest('.creative-editor'))return;const d=b.dataset;window.dispatchEvent(new CustomEvent('cewen:creative-request',{detail:{action:d.confirmDecision?'confirm-decision':d.objectEdit?'edit':d.objectReference?'reference':d.objectCopy?'copy':d.questTarget||d.documentQuest?'quest':d.questOpen?'open-quest':d.sequencePlay?'play':d.productionOpen?'production':d.documentModule?'catalog':'object',objectId:d.confirmDecision??d.objectOpen??d.objectEdit??d.objectReference??d.objectCopy??d.questTarget??d.questOpen??d.sequencePlay??d.productionOpen,documentId:d.documentModule??d.documentQuest,...(d.documentQuest?{anchor:{excerpt:window.getSelection()?.toString().trim()??''}}:{})}}));});
 }
 receive(snapshot:ProjectSnapshot){const changed=this.snapshot?.project.id!==snapshot.project.id;this.snapshot=snapshot;if(changed){this.selected='';this.disposeContent?.();}const notice=this.host.querySelector('[data-refresh-notice]');if(notice)notice.textContent='项目已更新。刷新本页读取最新内容；未提交输入不会被自动覆盖。';}
 private apply=(s:ProjectSnapshot)=>{this.snapshot=s;this.applyProject(s);};
 private index(){return buildCreativeIndex(this.snapshot??{documents:[]});}
 private error(error:unknown){const box=this.host.querySelector('[role=status]');if(box)box.textContent=(error as Error).message??String(error);}
 private writable(){if(!this.snapshot)throw new Error('请先创建或打开项目');if(this.snapshot.historical)throw new Error('历史只读，请回到最新版本');if(this.snapshot.project.format!==2)throw new Error('请先在副本升级到格式 2');return this.snapshot;}
 activate(tab:CreativeTab=this.tab){this.tab=tab;this.selected='';this.render();}
 tutorialNavigate(tab:CreativeTab,type?:string){this.tab=tab;this.selected=type?this.index().objects.find(o=>o.object.type===type)?.object.id??'':'';this.render();}
 deactivate(){this.disposeContent?.();this.disposeContent=undefined;}
 async handle(detail:{action:string;objectId?:string;documentId?:string;anchor?:Record<string,unknown>}){try{
  switch(detail.action){case 'confirm-decision':{const current=this.writable(),item=this.index().objects.find(o=>o.object.id===detail.objectId);if(!item)throw new Error('决定不存在');if(!confirm('确认这份决定？这只记录你的决定，不会自动采纳文档修改提案。'))break;this.apply(await creativeAction<ProjectSnapshot>(current.project.id,'decision-confirm',{requestId:crypto.randomUUID(),objectId:item.object.id,baseHash:item.hash,confirmed:true}));this.render();break;}case 'overview':this.activate();break;case 'catalog':this.catalog(detail.documentId);break;case 'edit':this.edit(detail.objectId!);break;case 'reference':this.reference(detail.objectId!);break;case 'copy':this.copy(detail.objectId!);break;case 'quest':this.createQuest(detail.objectId,detail.documentId,detail.anchor);break;case 'open-quest':this.tab='quests';this.selected=detail.objectId!;this.render();break;case 'play':this.tab='sequences';this.selected=detail.objectId!;this.render();break;case 'production':this.tab='production';this.selected=detail.objectId!;this.render();break;case 'object':this.tab='objects';this.selected=detail.objectId!;this.render();break;}
 }catch(e){this.error(e);}}
 private render(){this.host.scrollTop=0;const generation=++this.generation;this.disposeContent?.();this.disposeContent=undefined;const snapshot=this.snapshot,index=this.index();
  this.host.innerHTML=`<section class="creative-workspace"><header class="creative-heading"><div><small>CREATIVE WORKSPACE · 0.9 候选版</small><h1>${({objects:'模块与共享资料',quests:'Quest / 问策',sequences:'分镜与排演',production:'素材生产',presets:'预设与示例'})[this.tab]}</h1><p>预设只提供起步内容；地图、角色、剧情和分镜可以自由组合。</p></div><button class="primary-button" data-new-module>＋ 插入模块</button></header><nav class="creative-tabs" data-tutorial="creative-tabs">${(['objects','quests','sequences','production','presets'] as CreativeTab[]).map(t=>`<button data-tab="${t}" aria-pressed="${t===this.tab}">${({objects:'全部模块',quests:'Quest',sequences:'排演',production:'生产与回导',presets:'预设与示例'})[t]}</button>`).join('')}</nav><div class="creative-refresh"><span data-refresh-notice></span><button data-reload>刷新当前内容</button></div><p role="status"></p><div class="creative-content"></div></section>`;
  this.host.onclick=e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!b)return;if(b.dataset.tab)this.activate(b.dataset.tab as CreativeTab);if(b.hasAttribute('data-new-module'))this.catalog();if(b.hasAttribute('data-reload'))void this.reload();if(b.dataset.page){this.page=Number(b.dataset.page);this.render();}};
  const content=this.host.querySelector<HTMLElement>('.creative-content')!;
  if(!snapshot){content.innerHTML='<div class="creative-empty"><h2>建立第一个创作项目</h2><p>从综合示例了解 Quest、模块组合与分镜排演，或从空白开始。</p><button class="primary-button" data-new-project>选择预设并创建</button></div>';content.querySelector('button')!.onclick=()=>void openPresetDialog(undefined,this.apply);return;}
  if(snapshot.project.format!==2){content.innerHTML='<div class="creative-empty"><h2>原项目保持格式 1</h2><p>阅读、编辑与原有问询仍可使用。新模块与媒体需要在独立副本升级，不改原文件与旧历史。</p><button class="primary-button">选择目录并升级副本</button></div>';content.querySelector('button')!.onclick=()=>this.upgrade();return;}
  if(this.tab==='presets'){content.innerHTML=`<div class="creative-preset-grid">${presets.map(p=>`<article><h2>${p.title}</h2><p>${p.description}</p><small>示例：${p.sample}</small></article>`).join('')}</div><button class="primary-button" data-append>追加预设内容到本项目</button><button data-new-project>创建独立项目 / 练习副本</button>`;content.querySelector('[data-append]')!.addEventListener('click',()=>void openPresetDialog(snapshot,this.apply,true));content.querySelector('[data-new-project]')!.addEventListener('click',()=>void openPresetDialog(undefined,this.apply));return;}
  if(this.selected){const found=index.objects.find(o=>o.object.id===this.selected);if(!found){content.innerHTML='<p>对象不存在，请刷新或回到列表。</p>';return;}const back=document.createElement('button');back.className='creative-back';back.textContent='← 返回列表';back.onclick=()=>{this.selected='';this.render();};content.append(back);const body=document.createElement('div');content.append(body);
   if(this.tab==='quests'){void this.questDetail(body,found.object.id,generation).catch(e=>this.error(e));return;}
   if(this.tab==='sequences'){try{const player=new AnimaticPlayer(body,snapshot,index,found.object.id);this.disposeContent=()=>player.dispose();}catch(e){this.error(e);}return;}
   if(this.tab==='production'){const panel=new ProductionPanel(body,snapshot,found.object.id,this.apply);this.disposeContent=()=>panel.dispose();return;}
   body.innerHTML=objectCard(found.object,index);this.disposeContent=hydrateMedia(body,snapshot,index);const refs=document.createElement('section');refs.className='creative-references';refs.innerHTML=`<h3>使用此对象的位置</h3>${index.references.filter(r=>r.targetId===found.object.id).map(r=>`<p><button data-object-open="${h(r.ownerId)}">${h(index.objects.find(o=>o.object.id===r.ownerId)?.object.title??r.ownerId)}</button> · ${h(r.role)} · ${h(r.path)}</p>`).join('')||'<p>尚无引用</p>'}`;body.append(refs);const bridge=document.createElement('button');bridge.className='secondary-button';bridge.textContent='导出万类交接意图包（接口预留）';bridge.onclick=()=>{void creativeAction(snapshot.project.id,'wanlei-export',{objectIds:[found.object.id]}).then(data=>downloadText(found.object.id+'-wanlei.json',JSON.stringify(data,null,2))).catch(e=>this.error(e));};body.append(bridge);return;
  }
  const type=this.tab==='quests'?'quest':this.tab==='sequences'?'sequence':this.tab==='production'?'production':this.filter;
  const matches=queryObjects(index,{type,text:this.query,status:this.statusFilter,tag:this.tagFilter,relatedId:this.relatedFilter,questId:this.questFilter,missingMedia:this.missingOnly,offset:this.page*24,limit:24}),stats=creativeStatistics(index),items=matches.objects,start=matches.offset,total=matches.total;
  if(start>=total&&start>0){this.page=0;this.render();return;}

  content.innerHTML=`<div class="creative-list-toolbar">${this.tab==='objects'?`<label>模块<select data-type><option value="">全部类型</option>${[...moduleRegistry.values()].map(m=>`<option value="${m.type}" ${m.type===type?'selected':''}>${m.title}</option>`).join('')}<option value="dialogue">互动对白</option><option value="palette">色板</option></select></label>`:''}<label>查找<input data-query type="search" value="${h(this.query)}" placeholder="按标题与内容查找"/></label><span>${total} 个对象</span>${this.tab==='quests'?'<button data-create-quest class="primary-button">发起 Quest</button><button data-standalone>独立问题</button>':''}${this.tab==='production'?'<button data-prepare class="primary-button">准备生产任务</button><label class="creative-upload">导入媒体<input data-media type="file" accept="image/png,image/jpeg,image/webp,image/gif,audio/*"/></label>':''}</div><details class="creative-filter-details"><summary>状态、标签、关联与统计</summary><div class="creative-list-toolbar"><label>状态<select data-extra-filter="status"><option value="">全部</option><option value="draft">草稿</option><option value="confirmed">已确认</option><option value="archived">归档</option></select></label><label>标签<input data-extra-filter="tag" value="${h(this.tagFilter)}" list="creative-tags"/></label><datalist id="creative-tags">${[...new Set(index.objects.flatMap(o=>o.object.tags??[]))].map(tag=>`<option value="${h(tag)}"></option>`).join('')}</datalist><label>关联对象<select data-extra-filter="related"><option value="">不限</option>${index.objects.map(o=>`<option value="${h(o.object.id)}">${h(o.object.title)}</option>`).join('')}</select></label><label>Quest范围<select data-extra-filter="quest"><option value="">不限</option>${index.objects.filter(o=>o.object.type==='quest').map(o=>`<option value="${h(o.object.id)}">${h(o.object.title)}</option>`).join('')}</select></label><label><input data-extra-filter="missing" type="checkbox" ${this.missingOnly?'checked':''}/>只看缺少素材</label><button type="button" data-clear-extra>清除筛选</button></div><p>${stats.sourceObjects} 个源对象 · ${stats.referenceUses} 处引用 · ${stats.panels} 张连续分镜 · ${stats.uniqueMedia} 份去重媒体（${(stats.mediaBytes/1048576).toFixed(1)} MiB），引用实例不重复统计源数据。</p></details><div class="creative-grid">${items.map(o=>`<div>${objectCard(o.object,index,true)}<button class="creative-open" ${this.tab==='quests'?`data-quest-open="${h(o.object.id)}"`:this.tab==='sequences'?`data-sequence-play="${h(o.object.id)}"`:this.tab==='production'?`data-production-open="${h(o.object.id)}"`:`data-object-open="${h(o.object.id)}"`}>${this.tab==='sequences'?'打开排演':'打开详情'}</button></div>`).join('')||'<p class="creative-empty">此处还没有内容。可插入模块，或追加一个虚构示例。</p>'}</div><div class="creative-pagination"><button data-page="${Math.max(0,this.page-1)}" ${start===0?'disabled':''}>上一页</button><span>${total?start+1:0}–${Math.min(total,start+24)} / ${total}</span><button data-page="${this.page+1}" ${start+24>=total?'disabled':''}>下一页</button></div>`;
  for(const [key,value] of [['status',this.statusFilter],['related',this.relatedFilter],['quest',this.questFilter]]){const input=content.querySelector<HTMLSelectElement>(`[data-extra-filter="${key}"]`);if(input)input.value=value;}
  content.querySelectorAll<HTMLInputElement|HTMLSelectElement>('[data-extra-filter]').forEach(input=>input.addEventListener('change',()=>{const key=input.dataset.extraFilter!;if(key==='status')this.statusFilter=input.value;else if(key==='tag')this.tagFilter=input.value;else if(key==='related')this.relatedFilter=input.value;else if(key==='quest')this.questFilter=input.value;else this.missingOnly=(input as HTMLInputElement).checked;this.page=0;this.render();}));
  content.querySelector('[data-clear-extra]')?.addEventListener('click',()=>{this.statusFilter=this.tagFilter=this.relatedFilter=this.questFilter=this.query='';this.missingOnly=false;this.page=0;this.render();});
  content.querySelector('[data-type]')?.addEventListener('change',e=>{this.filter=(e.target as HTMLSelectElement).value;this.page=0;this.render();});content.querySelector('[data-query]')?.addEventListener('change',e=>{this.query=(e.target as HTMLInputElement).value;this.page=0;this.render();});
  content.querySelector('[data-create-quest]')?.addEventListener('click',()=>{try{this.createQuest();}catch(e){this.error(e);}});content.querySelector('[data-standalone]')?.addEventListener('click',()=>{content.replaceChildren();this.disposeContent=mountQuestions(content,snapshot,relatedQuestions(snapshot).filter(q=>!readHeader(q.text).metadata.questId),s=>{this.apply(s);this.render();});});content.querySelector('[data-prepare]')?.addEventListener('click',()=>{try{this.prepareProduction();}catch(e){this.error(e);}});
  content.querySelector('[data-media]')?.addEventListener('change',e=>{const file=(e.target as HTMLInputElement).files?.[0];if(file)void this.upload(file).catch(e=>this.error(e));});this.disposeContent=hydrateMedia(content,snapshot,index);
 }
 private async reload(){if(!this.snapshot)return;try{this.snapshot=await readProject(this.snapshot.project.id);this.applyProject(this.snapshot);this.render();}catch(e){this.error(e);}}
 private edit(id:string){const snapshot=this.writable(),index=this.index(),located=index.objects.find(o=>o.object.id===id);if(!located)throw new Error('对象不存在');if(['dialogue','palette'].includes(located.object.type)){window.dispatchEvent(new CustomEvent('cewen:read-document',{detail:located.documentId}));return;}openObjectEditor({object:located.object,index,snapshot,documentId:located.documentId,onSaved:s=>{this.apply(s);this.render();}});}
 private copy(id:string){const located=this.index().objects.find(o=>o.object.id===id);if(!located)return;const object=cloneCreativeObject(located.object,located.object.type+'-'+crypto.randomUUID().slice(0,12),()=> 'part-'+crypto.randomUUID().slice(0,12));openObjectEditor({object,index:this.index(),snapshot:this.writable(),isNew:true,onSaved:s=>{this.apply(s);this.render();window.dispatchEvent(new CustomEvent('cewen:tutorial-evidence',{detail:{name:'object-copied',projectId:s.project.id}}));}});}
 private reference(id:string){const object=moduleRegistry.get('reference')!.create('ref-'+crypto.randomUUID().slice(0,12),'共享引用');object.data.objectId=id;openObjectEditor({object,index:this.index(),snapshot:this.writable(),isNew:true,onSaved:s=>{this.apply(s);this.render();window.dispatchEvent(new CustomEvent('cewen:tutorial-evidence',{detail:{name:'object-referenced',projectId:s.project.id}}));}});}
 catalog(documentId?:string){try{const snapshot=this.writable(),dialog=document.createElement('dialog');dialog.className='project-dialog creative-catalog';dialog.innerHTML=`<header class="project-dialog-header"><div><h1>插入模块</h1><p>在任意文档使用任何模块，预设不限制能力。</p></div><button data-close>×</button></header><div class="creative-catalog-grid">${[...moduleRegistry.values()].filter(m=>!['production','media'].includes(m.type)).map(m=>`<button data-module="${m.type}"><strong>${m.title}</strong><span>${m.description}</span></button>`).join('')}</div><p>互动对白与色板继续使用原文档编辑器的插入入口。</p>`;dialog.onclick=e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(b?.hasAttribute('data-close')){dialog.close();dialog.remove();}if(b?.dataset.module){const o=moduleRegistry.get(b.dataset.module)!.create(b.dataset.module+'-'+crypto.randomUUID().slice(0,12));dialog.close();dialog.remove();openObjectEditor({object:o,index:this.index(),snapshot,documentId,isNew:true,onSaved:s=>{this.apply(s);this.render();}});}};document.body.append(dialog);dialog.showModal();}catch(e){this.error(e);}}
 private createQuest(objectId?:string,documentId?:string,anchor?:Record<string,unknown>){const snapshot=this.writable(),index=this.index(),dialog=document.createElement('dialog');dialog.className='project-dialog creative-editor';const selected=objectId?[objectId]:[],quote=asString(anchor?.excerpt)||window.getSelection()?.toString().trim()||'';
  dialog.innerHTML=`<header class="project-dialog-header"><div><h1>发起 Quest / 问策</h1><p>一个明确的创作目标，每轮聚焦少量关键问题。</p></div><button data-close>×</button></header><form><label>标题<input name="title" required maxlength="200" value="${objectId?'讨论：'+h(index.objects.find(o=>o.object.id===objectId)?.object.title):''}"/></label><label>需要解决的目标<textarea name="goal" required rows="3">${h(quote)}</textarea></label><label>范围与约束<textarea name="scope" rows="2"></textarea></label><label>关联对象<select name="targets" multiple size="5">${index.objects.filter(x=>!['media','production','quest'].includes(x.object.type)).map(x=>`<option value="${h(x.object.id)}" ${selected.includes(x.object.id)?'selected':''}>${h(x.object.title)} · ${h(x.object.type)}</option>`).join('')}</select></label><p class="creative-note">${documentId?'同时关联当前文档。':''}${quote?'已引用选区原话；正文后续变化时需核对定位。':''}不会自动生成用户答案。</p><p role="status"></p><button type="submit" class="primary-button">创建 Quest</button></form>`;const requestId=crypto.randomUUID(),questId='quest-'+crypto.randomUUID().slice(0,12);let busy=false;
  dialog.onclick=e=>{if((e.target as HTMLElement).closest('[data-close]')&&!busy){dialog.close();dialog.remove();}};dialog.onsubmit=e=>{e.preventDefault();if(busy)return;busy=true;const data=new FormData(dialog.querySelector('form')!);void creativeAction<ProjectSnapshot>(snapshot.project.id,'quest-create',{requestId,questId,title:data.get('title'),goal:data.get('goal'),scope:data.get('scope'),targetIds:data.getAll('targets'),documentIds:documentId??'',anchor:{...anchorFromText(snapshot,documentId??index.objects.find(o=>o.object.id===objectId)?.documentId??'',quote),...anchor,...(objectId?{objectId}:{})}}).then(s=>{this.apply(s);dialog.close();dialog.remove();window.dispatchEvent(new CustomEvent('cewen:tutorial-evidence',{detail:{name:'quest-created',projectId:snapshot.project.id,questId}}));this.tab='quests';this.selected=questId;this.render();}).catch(error=>{dialog.querySelector('[role=status]')!.textContent=error.message;}).finally(()=>busy=false);};document.body.append(dialog);dialog.showModal();
 }
 private async questDetail(host:HTMLElement,id:string,generation:number){const data=await creativeAction<{quest:CreativeObject;hash:string;revision:string;answerState:string;decisionState:string;decisions:{id:string;title:string;state:string}[];implementationState:string;proposals:{id:string;title:string;state:string;needsReview:boolean}[]}>(this.snapshot!.project.id,'quest-read',{questId:id});if(generation!==this.generation)return;const snapshot=this.snapshot!;host.innerHTML=`<section class="quest-detail" data-tutorial="quest-workspace"><header><small>${h(stateLabel(data.quest.data.state))} · ${h(stateLabel(data.answerState))} · ${h(stateLabel(data.decisionState))} · ${h(stateLabel(data.implementationState))}</small><h2>${h(data.quest.title)}</h2><p>${h(data.quest.data.goal)}</p><p>${h(data.quest.data.scope)}</p></header><div class="quest-actions"><button data-continue class="primary-button" data-tutorial="quest-continue">准备下一轮给 LLM</button><button data-import-round>接收本轮问题包</button><button data-review>审核修改提案</button><button data-object-edit="${h(id)}">范围 / 暂停 / 关闭</button></div><p class="creative-note">问答、决定与落实分开。提交答案不会自动唤醒所有 MCP 客户端；使用下一轮请求继续。</p><details><summary>轮次与提案状态</summary>${asRows(data.quest.data.rounds).map(r=>`<article><strong>第 ${h(r.number)} 轮</strong><p>${h(r.summary)}</p><small>来源修订 ${h(r.sourceRevision)}</small></article>`).join('')}${data.proposals.map(p=>`<p>${h(p.title)} · ${h(stateLabel(p.state))} ${p.needsReview?'· 后续内容变化，需复核':''}</p>`).join('')}</details><div class="quest-decisions">${data.decisions.map(d=>`<p>${h(d.title)} · ${h(stateLabel(d.state))}<button data-object-open="${h(d.id)}">查看决定</button></p>`).join('')}</div><div class="quest-question-host"></div><p role="status"></p></section>`;
  this.disposeContent=mountQuestions(host.querySelector('.quest-question-host')!,snapshot,relatedQuestions(snapshot,undefined,id),s=>{this.apply(s);this.render();});host.querySelector('[data-review]')!.addEventListener('click',this.review);
  host.querySelector('[data-continue]')!.addEventListener('click',()=>{const prompt=`请继续策问项目 ${snapshot.project.id} 中的 Quest ${id}。\n目标：${data.quest.data.goal}\n实际修订：${data.revision}\nQuest 哈希：${data.hash}\n\n先调用 cewen_quest_read；交接游标 ${data.revision} 可用于 cewen_quest_events。用 cewen_object_context 只读取相关对象与依据，保留用户原话。每轮优先 3～5 个问题；调用 cewen_quest_round 追加新一轮，勿代答，勿自行采纳提案。\n\n无策问工具时请明确说明，使用用户导出的问询包；不要宣称已连接。`;this.textDialog('下一轮协作请求',prompt,()=>creativeAction(this.snapshot!.project.id,'quest-read',{questId:id}).then(result=>downloadText(id+'-context.json',JSON.stringify(result,null,2))));});
  host.querySelector('[data-import-round]')!.addEventListener('click',()=>this.roundDialog(id,data.hash));
 }
 private textDialog(title:string,text:string,extra?:()=>Promise<unknown>){const dialog=document.createElement('dialog');dialog.className='project-dialog creative-editor';dialog.innerHTML=`<header class="project-dialog-header"><h2>${h(title)}</h2><button data-close>×</button></header><textarea rows="14">${h(text)}</textarea><p role="status"></p><footer><button data-copy>复制</button>${extra?'<button data-extra>导出完整上下文包</button>':''}</footer>`;dialog.onclick=e=>{const b=(e.target as HTMLElement).closest('button');if(b?.hasAttribute('data-close')){dialog.close();dialog.remove();}if(b?.hasAttribute('data-copy'))void navigator.clipboard.writeText(dialog.querySelector('textarea')!.value).then(()=>{dialog.querySelector('[role=status]')!.textContent='已复制';if(title==='下一轮协作请求')window.dispatchEvent(new CustomEvent('cewen:tutorial-evidence',{detail:{name:'quest-continuation',projectId:this.snapshot?.project.id}}));}).catch(e=>dialog.querySelector('[role=status]')!.textContent=e.message);if(b?.hasAttribute('data-extra'))void extra?.().catch(e=>dialog.querySelector('[role=status]')!.textContent=e.message);};document.body.append(dialog);dialog.showModal();}
 private roundDialog(questId:string,baseHash:string){const snapshot=this.writable(),dialog=document.createElement('dialog');dialog.className='project-dialog creative-editor';const requestId=crypto.randomUUID(),roundId='round-'+crypto.randomUUID().slice(0,12),questionId='q-'+crypto.randomUUID().slice(0,12);dialog.innerHTML=`<header class="project-dialog-header"><h2>接收 LLM 的问题包</h2><button data-close>×</button></header><p>接收问题不填写答案。可粘贴结构化包，或先录入一个手工问题。</p><form><label>本轮分析<textarea name="summary" rows="2"></textarea></label><label>问题标题<input name="title"/></label><label>背景<textarea name="background"></textarea></label><label>选项（每行一个）<textarea name="options"></textarea></label><details><summary>粘贴 LLM JSON 问题包</summary><textarea name="json" rows="8" placeholder='{"summary":"...","questions":[{"id":"q-new","title":"...","background":"...","options":["A","B"]}]}'></textarea></details><p role="status"></p><button class="primary-button">校验并发布本轮</button></form>`;dialog.onclick=e=>{if((e.target as HTMLElement).closest('[data-close]')){dialog.close();dialog.remove();}};dialog.onsubmit=e=>{e.preventDefault();const form=new FormData(dialog.querySelector('form')!);let payload:Record<string,unknown>;try{payload=form.get('json')?JSON.parse(String(form.get('json'))):{summary:form.get('summary'),questions:[{id:questionId,title:form.get('title'),background:form.get('background'),options:String(form.get('options')).split('\n').filter(Boolean)}]};}catch{dialog.querySelector('[role=status]')!.textContent='JSON 无法解析';return;}void creativeAction<ProjectSnapshot>(snapshot.project.id,'quest-round',{summary:payload.summary,questions:payload.questions,requestId,roundId,questId,baseHash}).then(s=>{this.apply(s);dialog.close();dialog.remove();this.render();}).catch(e=>dialog.querySelector('[role=status]')!.textContent=e.message);};document.body.append(dialog);dialog.showModal();}
 private async upload(file:File){const s=this.writable(),durationMs=await mediaInput(file),result=await uploadProjectMedia(s.project.id,file,{requestId:crypto.randomUUID(),permission:'用户直接导入；采用前核对来源许可',durationMs});this.apply(result.snapshot);this.tab='objects';this.selected=result.mediaId;this.render();}
 private prepareProduction(){
  const snapshot=this.writable(),dialog=document.createElement('dialog');dialog.className='project-dialog creative-editor';const index=this.index(),batchId='batch-'+crypto.randomUUID().slice(0,12);let requestId=crypto.randomUUID(),lastSignature='',busy=false;
  dialog.innerHTML=`<header class="project-dialog-header"><h2>准备素材生产任务</h2><button data-close>×</button></header><form><label>批次标题<input name="title" value="本轮素材生产" required/></label><label>本轮目标<textarea name="purpose"></textarea></label><label>对象 / 场次 / 排演范围<select name="targets" multiple size="8">${index.objects.filter(o=>['character','location','map','map-use','shot','speech','scene','sequence','storyline'].includes(o.object.type)).map(o=>`<option value="${h(o.object.id)}">${h(o.object.title)} · ${h(moduleRegistry.get(o.object.type)?.title)}</option>`).join('')}</select></label><label>生成范围<select name="scope"><option value="all">全部选定内容</option><option value="missing">仅缺失素材</option><option value="changed">仅依据变化或尚无生产基准</option></select></label><p class="creative-note">场次 / 排演会展开为镜头和台词。可以逐项勾选、改提示词；保存任务不会调用模型或计费。</p><button data-preview type="button">预览任务与提示词</button><div data-preview-content></div><p role="status"></p><button type="submit" class="primary-button" disabled>确认保存生产批次</button></form>`;
  let preparedTargets:string[]=[],preparedScope='all',preparedRevision:string|null=null;
  const feedback=(text:string)=>dialog.querySelector('[role=status]')!.textContent=text;
  dialog.onclick=e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!b||busy)return;if(b.hasAttribute('data-close')){dialog.close();dialog.remove();}if(b.hasAttribute('data-preview')){const form=new FormData(dialog.querySelector('form')!);preparedTargets=form.getAll('targets').map(String);preparedScope=String(form.get('scope'));busy=true;b.disabled=true;
   void creativeAction<{sourceRevision:string|null;jobs:{id:string;title:string;kind:string;prompt:string;referenceMediaIds:string[]}[]}>(snapshot.project.id,'production-preview',{batchId,targetIds:preparedTargets,scope:preparedScope}).then(result=>{preparedRevision=result.sourceRevision;dialog.querySelector('[data-preview-content]')!.innerHTML=result.jobs.map(j=>`<details data-preview-job="${h(j.id)}"><summary><label><input type="checkbox" name="jobs" value="${h(j.id)}" checked/>${h(j.title)} · ${j.kind==='voice'?'配音':'图片'} · ${j.referenceMediaIds.length} 份参考</label></summary><label>提示词（可修改）<textarea data-job-prompt rows="9">${h(j.prompt)}</textarea></label><label>负向提示词（产线不支持时明确提示）<textarea data-job-negative rows="2"></textarea></label></details>`).join('');dialog.querySelector<HTMLButtonElement>('[type=submit]')!.disabled=!result.jobs.length;feedback(result.jobs.length?`共 ${result.jobs.length} 项；请核对实际外发的提示词和参考。`:'当前范围没有需要生成的素材。');window.dispatchEvent(new CustomEvent('cewen:tutorial-evidence',{detail:{name:'production-previewed',projectId:snapshot.project.id}}));}).catch(e=>feedback(e.message)).finally(()=>{busy=false;b.disabled=false;});}};
  dialog.onchange=e=>{const el=e.target as HTMLInputElement;if(['targets','scope'].includes(el.name))dialog.querySelector<HTMLButtonElement>('[type=submit]')!.disabled=true;};
  dialog.onsubmit=e=>{e.preventDefault();if(busy)return;const data=new FormData(dialog.querySelector('form')!),targetIds=data.getAll('targets').map(String),scope=String(data.get('scope'));if(JSON.stringify(targetIds)!==JSON.stringify(preparedTargets)||scope!==preparedScope){feedback('范围已变化，请重新预览。');return;}const selectedJobIds=data.getAll('jobs').map(String);if(!selectedJobIds.length){feedback('请至少选择一个任务。');return;}
   const overrides:Record<string,{prompt:string;negativePrompt:string}>={};for(const row of dialog.querySelectorAll<HTMLElement>('[data-preview-job]'))if(selectedJobIds.includes(row.dataset.previewJob!))overrides[row.dataset.previewJob!]={prompt:row.querySelector<HTMLTextAreaElement>('[data-job-prompt]')!.value,negativePrompt:row.querySelector<HTMLTextAreaElement>('[data-job-negative]')!.value};
   const payload={batchId,title:data.get('title'),purpose:data.get('purpose'),targetIds,scope,selectedJobIds,overrides,baseRevision:preparedRevision},signature=JSON.stringify(payload);if(signature!==lastSignature){requestId=crypto.randomUUID();lastSignature=signature;}busy=true;
   void creativeAction<ProjectSnapshot>(snapshot.project.id,'production-prepare',{...payload,requestId}).then(next=>{this.apply(next);dialog.close();dialog.remove();this.tab='production';this.selected=batchId;this.render();window.dispatchEvent(new CustomEvent('cewen:tutorial-evidence',{detail:{name:'production-prepared',projectId:snapshot.project.id}}));}).catch(e=>feedback(e.message)).finally(()=>busy=false);
  };document.body.append(dialog);dialog.showModal();
 }

 private upgrade(){const snapshot=this.snapshot!,dialog=document.createElement('dialog');dialog.className='project-dialog creative-editor';dialog.innerHTML='<header class="project-dialog-header"><h2>在副本升级</h2><button data-close>×</button></header><p>创建完整副本，保留旧快照字节。成功后切换最近入口到新副本，原项目文件不修改。</p><form><label>副本保存父目录<input name="directory" required/></label><p role="status"></p><button class="primary-button">创建并升级副本</button></form>';prepareDirectoryFields(dialog);dialog.onclick=e=>{if((e.target as HTMLElement).closest('[data-close]')){dialog.close();dialog.remove();}};dialog.onsubmit=e=>{e.preventDefault();void projectAction<ProjectSnapshot>(snapshot.project.id,'upgrade-copy',{directory:new FormData(dialog.querySelector('form')!).get('directory')}).then(s=>{this.apply(s);dialog.close();dialog.remove();this.render();}).catch(e=>dialog.querySelector('[role=status]')!.textContent=e.message);};document.body.append(dialog);dialog.showModal();}
}
